// Code generated by ent, DO NOT EDIT.

package carpoolplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLTE(FieldID, id))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v float64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldTotalAmount, v))
}

// TargetMembers applies equality check predicate on the "target_members" field. It's identical to TargetMembersEQ.
func TargetMembers(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldTargetMembers, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldNote, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldRevision, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v float64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v float64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...float64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...float64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v float64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v float64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v float64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v float64) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLTE(FieldTotalAmount, v))
}

// TargetMembersEQ applies the EQ predicate on the "target_members" field.
func TargetMembersEQ(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldTargetMembers, v))
}

// TargetMembersNEQ applies the NEQ predicate on the "target_members" field.
func TargetMembersNEQ(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNEQ(FieldTargetMembers, v))
}

// TargetMembersIn applies the In predicate on the "target_members" field.
func TargetMembersIn(vs ...int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldIn(FieldTargetMembers, vs...))
}

// TargetMembersNotIn applies the NotIn predicate on the "target_members" field.
func TargetMembersNotIn(vs ...int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNotIn(FieldTargetMembers, vs...))
}

// TargetMembersGT applies the GT predicate on the "target_members" field.
func TargetMembersGT(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGT(FieldTargetMembers, v))
}

// TargetMembersGTE applies the GTE predicate on the "target_members" field.
func TargetMembersGTE(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGTE(FieldTargetMembers, v))
}

// TargetMembersLT applies the LT predicate on the "target_members" field.
func TargetMembersLT(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLT(FieldTargetMembers, v))
}

// TargetMembersLTE applies the LTE predicate on the "target_members" field.
func TargetMembersLTE(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLTE(FieldTargetMembers, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldContainsFold(FieldNote, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLTE(FieldRevision, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CarpoolPlan) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CarpoolPlan) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CarpoolPlan) predicate.CarpoolPlan {
	return predicate.CarpoolPlan(sql.NotPredicates(p))
}
