// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolplan"
)

// CarpoolPlanCreate is the builder for creating a CarpoolPlan entity.
type CarpoolPlanCreate struct {
	config
	mutation *CarpoolPlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTotalAmount sets the "total_amount" field.
func (_c *CarpoolPlanCreate) SetTotalAmount(v float64) *CarpoolPlanCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetTargetMembers sets the "target_members" field.
func (_c *CarpoolPlanCreate) SetTargetMembers(v int) *CarpoolPlanCreate {
	_c.mutation.SetTargetMembers(v)
	return _c
}

// SetNote sets the "note" field.
func (_c *CarpoolPlanCreate) SetNote(v string) *CarpoolPlanCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetRevision sets the "revision" field.
func (_c *CarpoolPlanCreate) SetRevision(v int) *CarpoolPlanCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *CarpoolPlanCreate) SetNillableRevision(v *int) *CarpoolPlanCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CarpoolPlanCreate) SetCreatedAt(v time.Time) *CarpoolPlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CarpoolPlanCreate) SetNillableCreatedAt(v *time.Time) *CarpoolPlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CarpoolPlanCreate) SetUpdatedAt(v time.Time) *CarpoolPlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CarpoolPlanCreate) SetNillableUpdatedAt(v *time.Time) *CarpoolPlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CarpoolPlanMutation object of the builder.
func (_c *CarpoolPlanCreate) Mutation() *CarpoolPlanMutation {
	return _c.mutation
}

// Save creates the CarpoolPlan in the database.
func (_c *CarpoolPlanCreate) Save(ctx context.Context) (*CarpoolPlan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CarpoolPlanCreate) SaveX(ctx context.Context) *CarpoolPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolPlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolPlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CarpoolPlanCreate) defaults() {
	if _, ok := _c.mutation.Revision(); !ok {
		v := carpoolplan.DefaultRevision
		_c.mutation.SetRevision(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := carpoolplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := carpoolplan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CarpoolPlanCreate) check() error {
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "CarpoolPlan.total_amount"`)}
	}
	if _, ok := _c.mutation.TargetMembers(); !ok {
		return &ValidationError{Name: "target_members", err: errors.New(`ent: missing required field "CarpoolPlan.target_members"`)}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "CarpoolPlan.note"`)}
	}
	if v, ok := _c.mutation.Note(); ok {
		if err := carpoolplan.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "CarpoolPlan.note": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "CarpoolPlan.revision"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CarpoolPlan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CarpoolPlan.updated_at"`)}
	}
	return nil
}

func (_c *CarpoolPlanCreate) sqlSave(ctx context.Context) (*CarpoolPlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CarpoolPlanCreate) createSpec() (*CarpoolPlan, *sqlgraph.CreateSpec) {
	var (
		_node = &CarpoolPlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(carpoolplan.Table, sqlgraph.NewFieldSpec(carpoolplan.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(carpoolplan.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.TargetMembers(); ok {
		_spec.SetField(carpoolplan.FieldTargetMembers, field.TypeInt, value)
		_node.TargetMembers = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(carpoolplan.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(carpoolplan.FieldRevision, field.TypeInt, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(carpoolplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolplan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolPlan.Create().
//		SetTotalAmount(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolPlanUpsert) {
//			SetTotalAmount(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolPlanCreate) OnConflict(opts ...sql.ConflictOption) *CarpoolPlanUpsertOne {
	_c.conflict = opts
	return &CarpoolPlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolPlanCreate) OnConflictColumns(columns ...string) *CarpoolPlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolPlanUpsertOne{
		create: _c,
	}
}

type (
	// CarpoolPlanUpsertOne is the builder for "upsert"-ing
	//  one CarpoolPlan node.
	CarpoolPlanUpsertOne struct {
		create *CarpoolPlanCreate
	}

	// CarpoolPlanUpsert is the "OnConflict" setter.
	CarpoolPlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetTotalAmount sets the "total_amount" field.
func (u *CarpoolPlanUpsert) SetTotalAmount(v float64) *CarpoolPlanUpsert {
	u.Set(carpoolplan.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *CarpoolPlanUpsert) UpdateTotalAmount() *CarpoolPlanUpsert {
	u.SetExcluded(carpoolplan.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *CarpoolPlanUpsert) AddTotalAmount(v float64) *CarpoolPlanUpsert {
	u.Add(carpoolplan.FieldTotalAmount, v)
	return u
}

// SetTargetMembers sets the "target_members" field.
func (u *CarpoolPlanUpsert) SetTargetMembers(v int) *CarpoolPlanUpsert {
	u.Set(carpoolplan.FieldTargetMembers, v)
	return u
}

// UpdateTargetMembers sets the "target_members" field to the value that was provided on create.
func (u *CarpoolPlanUpsert) UpdateTargetMembers() *CarpoolPlanUpsert {
	u.SetExcluded(carpoolplan.FieldTargetMembers)
	return u
}

// AddTargetMembers adds v to the "target_members" field.
func (u *CarpoolPlanUpsert) AddTargetMembers(v int) *CarpoolPlanUpsert {
	u.Add(carpoolplan.FieldTargetMembers, v)
	return u
}

// SetNote sets the "note" field.
func (u *CarpoolPlanUpsert) SetNote(v string) *CarpoolPlanUpsert {
	u.Set(carpoolplan.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *CarpoolPlanUpsert) UpdateNote() *CarpoolPlanUpsert {
	u.SetExcluded(carpoolplan.FieldNote)
	return u
}

// SetRevision sets the "revision" field.
func (u *CarpoolPlanUpsert) SetRevision(v int) *CarpoolPlanUpsert {
	u.Set(carpoolplan.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *CarpoolPlanUpsert) UpdateRevision() *CarpoolPlanUpsert {
	u.SetExcluded(carpoolplan.FieldRevision)
	return u
}

// AddRevision adds v to the "revision" field.
func (u *CarpoolPlanUpsert) AddRevision(v int) *CarpoolPlanUpsert {
	u.Add(carpoolplan.FieldRevision, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolPlanUpsert) SetUpdatedAt(v time.Time) *CarpoolPlanUpsert {
	u.Set(carpoolplan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolPlanUpsert) UpdateUpdatedAt() *CarpoolPlanUpsert {
	u.SetExcluded(carpoolplan.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CarpoolPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolPlanUpsertOne) UpdateNewValues() *CarpoolPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(carpoolplan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolPlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CarpoolPlanUpsertOne) Ignore() *CarpoolPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolPlanUpsertOne) DoNothing() *CarpoolPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolPlanCreate.OnConflict
// documentation for more info.
func (u *CarpoolPlanUpsertOne) Update(set func(*CarpoolPlanUpsert)) *CarpoolPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *CarpoolPlanUpsertOne) SetTotalAmount(v float64) *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *CarpoolPlanUpsertOne) AddTotalAmount(v float64) *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *CarpoolPlanUpsertOne) UpdateTotalAmount() *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetTargetMembers sets the "target_members" field.
func (u *CarpoolPlanUpsertOne) SetTargetMembers(v int) *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.SetTargetMembers(v)
	})
}

// AddTargetMembers adds v to the "target_members" field.
func (u *CarpoolPlanUpsertOne) AddTargetMembers(v int) *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.AddTargetMembers(v)
	})
}

// UpdateTargetMembers sets the "target_members" field to the value that was provided on create.
func (u *CarpoolPlanUpsertOne) UpdateTargetMembers() *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.UpdateTargetMembers()
	})
}

// SetNote sets the "note" field.
func (u *CarpoolPlanUpsertOne) SetNote(v string) *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *CarpoolPlanUpsertOne) UpdateNote() *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.UpdateNote()
	})
}

// SetRevision sets the "revision" field.
func (u *CarpoolPlanUpsertOne) SetRevision(v int) *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *CarpoolPlanUpsertOne) AddRevision(v int) *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *CarpoolPlanUpsertOne) UpdateRevision() *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.UpdateRevision()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolPlanUpsertOne) SetUpdatedAt(v time.Time) *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolPlanUpsertOne) UpdateUpdatedAt() *CarpoolPlanUpsertOne {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolPlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolPlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolPlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CarpoolPlanUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CarpoolPlanUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CarpoolPlanCreateBulk is the builder for creating many CarpoolPlan entities in bulk.
type CarpoolPlanCreateBulk struct {
	config
	err      error
	builders []*CarpoolPlanCreate
	conflict []sql.ConflictOption
}

// Save creates the CarpoolPlan entities in the database.
func (_c *CarpoolPlanCreateBulk) Save(ctx context.Context) ([]*CarpoolPlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CarpoolPlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarpoolPlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CarpoolPlanCreateBulk) SaveX(ctx context.Context) []*CarpoolPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolPlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolPlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolPlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolPlanUpsert) {
//			SetTotalAmount(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolPlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *CarpoolPlanUpsertBulk {
	_c.conflict = opts
	return &CarpoolPlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolPlanCreateBulk) OnConflictColumns(columns ...string) *CarpoolPlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolPlanUpsertBulk{
		create: _c,
	}
}

// CarpoolPlanUpsertBulk is the builder for "upsert"-ing
// a bulk of CarpoolPlan nodes.
type CarpoolPlanUpsertBulk struct {
	create *CarpoolPlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CarpoolPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolPlanUpsertBulk) UpdateNewValues() *CarpoolPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(carpoolplan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolPlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CarpoolPlanUpsertBulk) Ignore() *CarpoolPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolPlanUpsertBulk) DoNothing() *CarpoolPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolPlanCreateBulk.OnConflict
// documentation for more info.
func (u *CarpoolPlanUpsertBulk) Update(set func(*CarpoolPlanUpsert)) *CarpoolPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *CarpoolPlanUpsertBulk) SetTotalAmount(v float64) *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *CarpoolPlanUpsertBulk) AddTotalAmount(v float64) *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *CarpoolPlanUpsertBulk) UpdateTotalAmount() *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetTargetMembers sets the "target_members" field.
func (u *CarpoolPlanUpsertBulk) SetTargetMembers(v int) *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.SetTargetMembers(v)
	})
}

// AddTargetMembers adds v to the "target_members" field.
func (u *CarpoolPlanUpsertBulk) AddTargetMembers(v int) *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.AddTargetMembers(v)
	})
}

// UpdateTargetMembers sets the "target_members" field to the value that was provided on create.
func (u *CarpoolPlanUpsertBulk) UpdateTargetMembers() *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.UpdateTargetMembers()
	})
}

// SetNote sets the "note" field.
func (u *CarpoolPlanUpsertBulk) SetNote(v string) *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *CarpoolPlanUpsertBulk) UpdateNote() *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.UpdateNote()
	})
}

// SetRevision sets the "revision" field.
func (u *CarpoolPlanUpsertBulk) SetRevision(v int) *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *CarpoolPlanUpsertBulk) AddRevision(v int) *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *CarpoolPlanUpsertBulk) UpdateRevision() *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.UpdateRevision()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolPlanUpsertBulk) SetUpdatedAt(v time.Time) *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolPlanUpsertBulk) UpdateUpdatedAt() *CarpoolPlanUpsertBulk {
	return u.Update(func(s *CarpoolPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolPlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CarpoolPlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolPlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolPlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
