// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolgroup"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CarpoolGroupUpdate is the builder for updating CarpoolGroup entities.
type CarpoolGroupUpdate struct {
	config
	hooks    []Hook
	mutation *CarpoolGroupMutation
}

// Where appends a list predicates to the CarpoolGroupUpdate builder.
func (_u *CarpoolGroupUpdate) Where(ps ...predicate.CarpoolGroup) *CarpoolGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCarpoolPlanID sets the "carpool_plan_id" field.
func (_u *CarpoolGroupUpdate) SetCarpoolPlanID(v int64) *CarpoolGroupUpdate {
	_u.mutation.ResetCarpoolPlanID()
	_u.mutation.SetCarpoolPlanID(v)
	return _u
}

// SetNillableCarpoolPlanID sets the "carpool_plan_id" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableCarpoolPlanID(v *int64) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetCarpoolPlanID(*v)
	}
	return _u
}

// AddCarpoolPlanID adds value to the "carpool_plan_id" field.
func (_u *CarpoolGroupUpdate) AddCarpoolPlanID(v int64) *CarpoolGroupUpdate {
	_u.mutation.AddCarpoolPlanID(v)
	return _u
}

// SetCarpoolPlanRevision sets the "carpool_plan_revision" field.
func (_u *CarpoolGroupUpdate) SetCarpoolPlanRevision(v int) *CarpoolGroupUpdate {
	_u.mutation.ResetCarpoolPlanRevision()
	_u.mutation.SetCarpoolPlanRevision(v)
	return _u
}

// SetNillableCarpoolPlanRevision sets the "carpool_plan_revision" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableCarpoolPlanRevision(v *int) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetCarpoolPlanRevision(*v)
	}
	return _u
}

// AddCarpoolPlanRevision adds value to the "carpool_plan_revision" field.
func (_u *CarpoolGroupUpdate) AddCarpoolPlanRevision(v int) *CarpoolGroupUpdate {
	_u.mutation.AddCarpoolPlanRevision(v)
	return _u
}

// SetTargetMembers sets the "target_members" field.
func (_u *CarpoolGroupUpdate) SetTargetMembers(v int) *CarpoolGroupUpdate {
	_u.mutation.ResetTargetMembers()
	_u.mutation.SetTargetMembers(v)
	return _u
}

// SetNillableTargetMembers sets the "target_members" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableTargetMembers(v *int) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetTargetMembers(*v)
	}
	return _u
}

// AddTargetMembers adds value to the "target_members" field.
func (_u *CarpoolGroupUpdate) AddTargetMembers(v int) *CarpoolGroupUpdate {
	_u.mutation.AddTargetMembers(v)
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *CarpoolGroupUpdate) SetTotalAmount(v float64) *CarpoolGroupUpdate {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableTotalAmount(v *float64) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *CarpoolGroupUpdate) AddTotalAmount(v float64) *CarpoolGroupUpdate {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetPricePerMember sets the "price_per_member" field.
func (_u *CarpoolGroupUpdate) SetPricePerMember(v float64) *CarpoolGroupUpdate {
	_u.mutation.ResetPricePerMember()
	_u.mutation.SetPricePerMember(v)
	return _u
}

// SetNillablePricePerMember sets the "price_per_member" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillablePricePerMember(v *float64) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetPricePerMember(*v)
	}
	return _u
}

// AddPricePerMember adds value to the "price_per_member" field.
func (_u *CarpoolGroupUpdate) AddPricePerMember(v float64) *CarpoolGroupUpdate {
	_u.mutation.AddPricePerMember(v)
	return _u
}

// SetPlanNote sets the "plan_note" field.
func (_u *CarpoolGroupUpdate) SetPlanNote(v string) *CarpoolGroupUpdate {
	_u.mutation.SetPlanNote(v)
	return _u
}

// SetNillablePlanNote sets the "plan_note" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillablePlanNote(v *string) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetPlanNote(*v)
	}
	return _u
}

// SetMemberCount sets the "member_count" field.
func (_u *CarpoolGroupUpdate) SetMemberCount(v int) *CarpoolGroupUpdate {
	_u.mutation.ResetMemberCount()
	_u.mutation.SetMemberCount(v)
	return _u
}

// SetNillableMemberCount sets the "member_count" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableMemberCount(v *int) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetMemberCount(*v)
	}
	return _u
}

// AddMemberCount adds value to the "member_count" field.
func (_u *CarpoolGroupUpdate) AddMemberCount(v int) *CarpoolGroupUpdate {
	_u.mutation.AddMemberCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CarpoolGroupUpdate) SetStatus(v string) *CarpoolGroupUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableStatus(v *string) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOpenKey sets the "open_key" field.
func (_u *CarpoolGroupUpdate) SetOpenKey(v string) *CarpoolGroupUpdate {
	_u.mutation.SetOpenKey(v)
	return _u
}

// SetNillableOpenKey sets the "open_key" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableOpenKey(v *string) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetOpenKey(*v)
	}
	return _u
}

// ClearOpenKey clears the value of the "open_key" field.
func (_u *CarpoolGroupUpdate) ClearOpenKey() *CarpoolGroupUpdate {
	_u.mutation.ClearOpenKey()
	return _u
}

// SetStatusReason sets the "status_reason" field.
func (_u *CarpoolGroupUpdate) SetStatusReason(v string) *CarpoolGroupUpdate {
	_u.mutation.SetStatusReason(v)
	return _u
}

// SetNillableStatusReason sets the "status_reason" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableStatusReason(v *string) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetStatusReason(*v)
	}
	return _u
}

// ClearStatusReason clears the value of the "status_reason" field.
func (_u *CarpoolGroupUpdate) ClearStatusReason() *CarpoolGroupUpdate {
	_u.mutation.ClearStatusReason()
	return _u
}

// SetDeadlineAt sets the "deadline_at" field.
func (_u *CarpoolGroupUpdate) SetDeadlineAt(v time.Time) *CarpoolGroupUpdate {
	_u.mutation.SetDeadlineAt(v)
	return _u
}

// SetNillableDeadlineAt sets the "deadline_at" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableDeadlineAt(v *time.Time) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetDeadlineAt(*v)
	}
	return _u
}

// ClearDeadlineAt clears the value of the "deadline_at" field.
func (_u *CarpoolGroupUpdate) ClearDeadlineAt() *CarpoolGroupUpdate {
	_u.mutation.ClearDeadlineAt()
	return _u
}

// SetFormedAt sets the "formed_at" field.
func (_u *CarpoolGroupUpdate) SetFormedAt(v time.Time) *CarpoolGroupUpdate {
	_u.mutation.SetFormedAt(v)
	return _u
}

// SetNillableFormedAt sets the "formed_at" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableFormedAt(v *time.Time) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetFormedAt(*v)
	}
	return _u
}

// ClearFormedAt clears the value of the "formed_at" field.
func (_u *CarpoolGroupUpdate) ClearFormedAt() *CarpoolGroupUpdate {
	_u.mutation.ClearFormedAt()
	return _u
}

// SetOpenedAt sets the "opened_at" field.
func (_u *CarpoolGroupUpdate) SetOpenedAt(v time.Time) *CarpoolGroupUpdate {
	_u.mutation.SetOpenedAt(v)
	return _u
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableOpenedAt(v *time.Time) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetOpenedAt(*v)
	}
	return _u
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (_u *CarpoolGroupUpdate) ClearOpenedAt() *CarpoolGroupUpdate {
	_u.mutation.ClearOpenedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CarpoolGroupUpdate) SetExpiresAt(v time.Time) *CarpoolGroupUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CarpoolGroupUpdate) SetNillableExpiresAt(v *time.Time) *CarpoolGroupUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CarpoolGroupUpdate) ClearExpiresAt() *CarpoolGroupUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CarpoolGroupUpdate) SetUpdatedAt(v time.Time) *CarpoolGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddOrderIDs adds the "orders" edge to the PaymentOrder entity by IDs.
func (_u *CarpoolGroupUpdate) AddOrderIDs(ids ...int64) *CarpoolGroupUpdate {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the PaymentOrder entity.
func (_u *CarpoolGroupUpdate) AddOrders(v ...*PaymentOrder) *CarpoolGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the CarpoolGroupMutation object of the builder.
func (_u *CarpoolGroupUpdate) Mutation() *CarpoolGroupMutation {
	return _u.mutation
}

// ClearOrders clears all "orders" edges to the PaymentOrder entity.
func (_u *CarpoolGroupUpdate) ClearOrders() *CarpoolGroupUpdate {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to PaymentOrder entities by IDs.
func (_u *CarpoolGroupUpdate) RemoveOrderIDs(ids ...int64) *CarpoolGroupUpdate {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to PaymentOrder entities.
func (_u *CarpoolGroupUpdate) RemoveOrders(v ...*PaymentOrder) *CarpoolGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CarpoolGroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CarpoolGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CarpoolGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CarpoolGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CarpoolGroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := carpoolgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CarpoolGroupUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := carpoolgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CarpoolGroup.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OpenKey(); ok {
		if err := carpoolgroup.OpenKeyValidator(v); err != nil {
			return &ValidationError{Name: "open_key", err: fmt.Errorf(`ent: validator failed for field "CarpoolGroup.open_key": %w`, err)}
		}
	}
	return nil
}

func (_u *CarpoolGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carpoolgroup.Table, carpoolgroup.Columns, sqlgraph.NewFieldSpec(carpoolgroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CarpoolPlanID(); ok {
		_spec.SetField(carpoolgroup.FieldCarpoolPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCarpoolPlanID(); ok {
		_spec.AddField(carpoolgroup.FieldCarpoolPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CarpoolPlanRevision(); ok {
		_spec.SetField(carpoolgroup.FieldCarpoolPlanRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCarpoolPlanRevision(); ok {
		_spec.AddField(carpoolgroup.FieldCarpoolPlanRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetMembers(); ok {
		_spec.SetField(carpoolgroup.FieldTargetMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetMembers(); ok {
		_spec.AddField(carpoolgroup.FieldTargetMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(carpoolgroup.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(carpoolgroup.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PricePerMember(); ok {
		_spec.SetField(carpoolgroup.FieldPricePerMember, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPricePerMember(); ok {
		_spec.AddField(carpoolgroup.FieldPricePerMember, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PlanNote(); ok {
		_spec.SetField(carpoolgroup.FieldPlanNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberCount(); ok {
		_spec.SetField(carpoolgroup.FieldMemberCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMemberCount(); ok {
		_spec.AddField(carpoolgroup.FieldMemberCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(carpoolgroup.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpenKey(); ok {
		_spec.SetField(carpoolgroup.FieldOpenKey, field.TypeString, value)
	}
	if _u.mutation.OpenKeyCleared() {
		_spec.ClearField(carpoolgroup.FieldOpenKey, field.TypeString)
	}
	if value, ok := _u.mutation.StatusReason(); ok {
		_spec.SetField(carpoolgroup.FieldStatusReason, field.TypeString, value)
	}
	if _u.mutation.StatusReasonCleared() {
		_spec.ClearField(carpoolgroup.FieldStatusReason, field.TypeString)
	}
	if value, ok := _u.mutation.DeadlineAt(); ok {
		_spec.SetField(carpoolgroup.FieldDeadlineAt, field.TypeTime, value)
	}
	if _u.mutation.DeadlineAtCleared() {
		_spec.ClearField(carpoolgroup.FieldDeadlineAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FormedAt(); ok {
		_spec.SetField(carpoolgroup.FieldFormedAt, field.TypeTime, value)
	}
	if _u.mutation.FormedAtCleared() {
		_spec.ClearField(carpoolgroup.FieldFormedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OpenedAt(); ok {
		_spec.SetField(carpoolgroup.FieldOpenedAt, field.TypeTime, value)
	}
	if _u.mutation.OpenedAtCleared() {
		_spec.ClearField(carpoolgroup.FieldOpenedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(carpoolgroup.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(carpoolgroup.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolgroup.OrdersTable,
			Columns: []string{carpoolgroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolgroup.OrdersTable,
			Columns: []string{carpoolgroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolgroup.OrdersTable,
			Columns: []string{carpoolgroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carpoolgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CarpoolGroupUpdateOne is the builder for updating a single CarpoolGroup entity.
type CarpoolGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CarpoolGroupMutation
}

// SetCarpoolPlanID sets the "carpool_plan_id" field.
func (_u *CarpoolGroupUpdateOne) SetCarpoolPlanID(v int64) *CarpoolGroupUpdateOne {
	_u.mutation.ResetCarpoolPlanID()
	_u.mutation.SetCarpoolPlanID(v)
	return _u
}

// SetNillableCarpoolPlanID sets the "carpool_plan_id" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableCarpoolPlanID(v *int64) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetCarpoolPlanID(*v)
	}
	return _u
}

// AddCarpoolPlanID adds value to the "carpool_plan_id" field.
func (_u *CarpoolGroupUpdateOne) AddCarpoolPlanID(v int64) *CarpoolGroupUpdateOne {
	_u.mutation.AddCarpoolPlanID(v)
	return _u
}

// SetCarpoolPlanRevision sets the "carpool_plan_revision" field.
func (_u *CarpoolGroupUpdateOne) SetCarpoolPlanRevision(v int) *CarpoolGroupUpdateOne {
	_u.mutation.ResetCarpoolPlanRevision()
	_u.mutation.SetCarpoolPlanRevision(v)
	return _u
}

// SetNillableCarpoolPlanRevision sets the "carpool_plan_revision" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableCarpoolPlanRevision(v *int) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetCarpoolPlanRevision(*v)
	}
	return _u
}

// AddCarpoolPlanRevision adds value to the "carpool_plan_revision" field.
func (_u *CarpoolGroupUpdateOne) AddCarpoolPlanRevision(v int) *CarpoolGroupUpdateOne {
	_u.mutation.AddCarpoolPlanRevision(v)
	return _u
}

// SetTargetMembers sets the "target_members" field.
func (_u *CarpoolGroupUpdateOne) SetTargetMembers(v int) *CarpoolGroupUpdateOne {
	_u.mutation.ResetTargetMembers()
	_u.mutation.SetTargetMembers(v)
	return _u
}

// SetNillableTargetMembers sets the "target_members" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableTargetMembers(v *int) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetTargetMembers(*v)
	}
	return _u
}

// AddTargetMembers adds value to the "target_members" field.
func (_u *CarpoolGroupUpdateOne) AddTargetMembers(v int) *CarpoolGroupUpdateOne {
	_u.mutation.AddTargetMembers(v)
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *CarpoolGroupUpdateOne) SetTotalAmount(v float64) *CarpoolGroupUpdateOne {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableTotalAmount(v *float64) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *CarpoolGroupUpdateOne) AddTotalAmount(v float64) *CarpoolGroupUpdateOne {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetPricePerMember sets the "price_per_member" field.
func (_u *CarpoolGroupUpdateOne) SetPricePerMember(v float64) *CarpoolGroupUpdateOne {
	_u.mutation.ResetPricePerMember()
	_u.mutation.SetPricePerMember(v)
	return _u
}

// SetNillablePricePerMember sets the "price_per_member" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillablePricePerMember(v *float64) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetPricePerMember(*v)
	}
	return _u
}

// AddPricePerMember adds value to the "price_per_member" field.
func (_u *CarpoolGroupUpdateOne) AddPricePerMember(v float64) *CarpoolGroupUpdateOne {
	_u.mutation.AddPricePerMember(v)
	return _u
}

// SetPlanNote sets the "plan_note" field.
func (_u *CarpoolGroupUpdateOne) SetPlanNote(v string) *CarpoolGroupUpdateOne {
	_u.mutation.SetPlanNote(v)
	return _u
}

// SetNillablePlanNote sets the "plan_note" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillablePlanNote(v *string) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetPlanNote(*v)
	}
	return _u
}

// SetMemberCount sets the "member_count" field.
func (_u *CarpoolGroupUpdateOne) SetMemberCount(v int) *CarpoolGroupUpdateOne {
	_u.mutation.ResetMemberCount()
	_u.mutation.SetMemberCount(v)
	return _u
}

// SetNillableMemberCount sets the "member_count" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableMemberCount(v *int) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetMemberCount(*v)
	}
	return _u
}

// AddMemberCount adds value to the "member_count" field.
func (_u *CarpoolGroupUpdateOne) AddMemberCount(v int) *CarpoolGroupUpdateOne {
	_u.mutation.AddMemberCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CarpoolGroupUpdateOne) SetStatus(v string) *CarpoolGroupUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableStatus(v *string) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOpenKey sets the "open_key" field.
func (_u *CarpoolGroupUpdateOne) SetOpenKey(v string) *CarpoolGroupUpdateOne {
	_u.mutation.SetOpenKey(v)
	return _u
}

// SetNillableOpenKey sets the "open_key" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableOpenKey(v *string) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetOpenKey(*v)
	}
	return _u
}

// ClearOpenKey clears the value of the "open_key" field.
func (_u *CarpoolGroupUpdateOne) ClearOpenKey() *CarpoolGroupUpdateOne {
	_u.mutation.ClearOpenKey()
	return _u
}

// SetStatusReason sets the "status_reason" field.
func (_u *CarpoolGroupUpdateOne) SetStatusReason(v string) *CarpoolGroupUpdateOne {
	_u.mutation.SetStatusReason(v)
	return _u
}

// SetNillableStatusReason sets the "status_reason" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableStatusReason(v *string) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetStatusReason(*v)
	}
	return _u
}

// ClearStatusReason clears the value of the "status_reason" field.
func (_u *CarpoolGroupUpdateOne) ClearStatusReason() *CarpoolGroupUpdateOne {
	_u.mutation.ClearStatusReason()
	return _u
}

// SetDeadlineAt sets the "deadline_at" field.
func (_u *CarpoolGroupUpdateOne) SetDeadlineAt(v time.Time) *CarpoolGroupUpdateOne {
	_u.mutation.SetDeadlineAt(v)
	return _u
}

// SetNillableDeadlineAt sets the "deadline_at" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableDeadlineAt(v *time.Time) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetDeadlineAt(*v)
	}
	return _u
}

// ClearDeadlineAt clears the value of the "deadline_at" field.
func (_u *CarpoolGroupUpdateOne) ClearDeadlineAt() *CarpoolGroupUpdateOne {
	_u.mutation.ClearDeadlineAt()
	return _u
}

// SetFormedAt sets the "formed_at" field.
func (_u *CarpoolGroupUpdateOne) SetFormedAt(v time.Time) *CarpoolGroupUpdateOne {
	_u.mutation.SetFormedAt(v)
	return _u
}

// SetNillableFormedAt sets the "formed_at" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableFormedAt(v *time.Time) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetFormedAt(*v)
	}
	return _u
}

// ClearFormedAt clears the value of the "formed_at" field.
func (_u *CarpoolGroupUpdateOne) ClearFormedAt() *CarpoolGroupUpdateOne {
	_u.mutation.ClearFormedAt()
	return _u
}

// SetOpenedAt sets the "opened_at" field.
func (_u *CarpoolGroupUpdateOne) SetOpenedAt(v time.Time) *CarpoolGroupUpdateOne {
	_u.mutation.SetOpenedAt(v)
	return _u
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableOpenedAt(v *time.Time) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetOpenedAt(*v)
	}
	return _u
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (_u *CarpoolGroupUpdateOne) ClearOpenedAt() *CarpoolGroupUpdateOne {
	_u.mutation.ClearOpenedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CarpoolGroupUpdateOne) SetExpiresAt(v time.Time) *CarpoolGroupUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CarpoolGroupUpdateOne) SetNillableExpiresAt(v *time.Time) *CarpoolGroupUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CarpoolGroupUpdateOne) ClearExpiresAt() *CarpoolGroupUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CarpoolGroupUpdateOne) SetUpdatedAt(v time.Time) *CarpoolGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddOrderIDs adds the "orders" edge to the PaymentOrder entity by IDs.
func (_u *CarpoolGroupUpdateOne) AddOrderIDs(ids ...int64) *CarpoolGroupUpdateOne {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the PaymentOrder entity.
func (_u *CarpoolGroupUpdateOne) AddOrders(v ...*PaymentOrder) *CarpoolGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the CarpoolGroupMutation object of the builder.
func (_u *CarpoolGroupUpdateOne) Mutation() *CarpoolGroupMutation {
	return _u.mutation
}

// ClearOrders clears all "orders" edges to the PaymentOrder entity.
func (_u *CarpoolGroupUpdateOne) ClearOrders() *CarpoolGroupUpdateOne {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to PaymentOrder entities by IDs.
func (_u *CarpoolGroupUpdateOne) RemoveOrderIDs(ids ...int64) *CarpoolGroupUpdateOne {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to PaymentOrder entities.
func (_u *CarpoolGroupUpdateOne) RemoveOrders(v ...*PaymentOrder) *CarpoolGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Where appends a list predicates to the CarpoolGroupUpdate builder.
func (_u *CarpoolGroupUpdateOne) Where(ps ...predicate.CarpoolGroup) *CarpoolGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CarpoolGroupUpdateOne) Select(field string, fields ...string) *CarpoolGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CarpoolGroup entity.
func (_u *CarpoolGroupUpdateOne) Save(ctx context.Context) (*CarpoolGroup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CarpoolGroupUpdateOne) SaveX(ctx context.Context) *CarpoolGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CarpoolGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CarpoolGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CarpoolGroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := carpoolgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CarpoolGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := carpoolgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CarpoolGroup.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OpenKey(); ok {
		if err := carpoolgroup.OpenKeyValidator(v); err != nil {
			return &ValidationError{Name: "open_key", err: fmt.Errorf(`ent: validator failed for field "CarpoolGroup.open_key": %w`, err)}
		}
	}
	return nil
}

func (_u *CarpoolGroupUpdateOne) sqlSave(ctx context.Context) (_node *CarpoolGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carpoolgroup.Table, carpoolgroup.Columns, sqlgraph.NewFieldSpec(carpoolgroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CarpoolGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carpoolgroup.FieldID)
		for _, f := range fields {
			if !carpoolgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != carpoolgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CarpoolPlanID(); ok {
		_spec.SetField(carpoolgroup.FieldCarpoolPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCarpoolPlanID(); ok {
		_spec.AddField(carpoolgroup.FieldCarpoolPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CarpoolPlanRevision(); ok {
		_spec.SetField(carpoolgroup.FieldCarpoolPlanRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCarpoolPlanRevision(); ok {
		_spec.AddField(carpoolgroup.FieldCarpoolPlanRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetMembers(); ok {
		_spec.SetField(carpoolgroup.FieldTargetMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetMembers(); ok {
		_spec.AddField(carpoolgroup.FieldTargetMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(carpoolgroup.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(carpoolgroup.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PricePerMember(); ok {
		_spec.SetField(carpoolgroup.FieldPricePerMember, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPricePerMember(); ok {
		_spec.AddField(carpoolgroup.FieldPricePerMember, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PlanNote(); ok {
		_spec.SetField(carpoolgroup.FieldPlanNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberCount(); ok {
		_spec.SetField(carpoolgroup.FieldMemberCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMemberCount(); ok {
		_spec.AddField(carpoolgroup.FieldMemberCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(carpoolgroup.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpenKey(); ok {
		_spec.SetField(carpoolgroup.FieldOpenKey, field.TypeString, value)
	}
	if _u.mutation.OpenKeyCleared() {
		_spec.ClearField(carpoolgroup.FieldOpenKey, field.TypeString)
	}
	if value, ok := _u.mutation.StatusReason(); ok {
		_spec.SetField(carpoolgroup.FieldStatusReason, field.TypeString, value)
	}
	if _u.mutation.StatusReasonCleared() {
		_spec.ClearField(carpoolgroup.FieldStatusReason, field.TypeString)
	}
	if value, ok := _u.mutation.DeadlineAt(); ok {
		_spec.SetField(carpoolgroup.FieldDeadlineAt, field.TypeTime, value)
	}
	if _u.mutation.DeadlineAtCleared() {
		_spec.ClearField(carpoolgroup.FieldDeadlineAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FormedAt(); ok {
		_spec.SetField(carpoolgroup.FieldFormedAt, field.TypeTime, value)
	}
	if _u.mutation.FormedAtCleared() {
		_spec.ClearField(carpoolgroup.FieldFormedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OpenedAt(); ok {
		_spec.SetField(carpoolgroup.FieldOpenedAt, field.TypeTime, value)
	}
	if _u.mutation.OpenedAtCleared() {
		_spec.ClearField(carpoolgroup.FieldOpenedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(carpoolgroup.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(carpoolgroup.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolgroup.OrdersTable,
			Columns: []string{carpoolgroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolgroup.OrdersTable,
			Columns: []string{carpoolgroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolgroup.OrdersTable,
			Columns: []string{carpoolgroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CarpoolGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carpoolgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
