// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolplan"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CarpoolPlanDelete is the builder for deleting a CarpoolPlan entity.
type CarpoolPlanDelete struct {
	config
	hooks    []Hook
	mutation *CarpoolPlanMutation
}

// Where appends a list predicates to the CarpoolPlanDelete builder.
func (_d *CarpoolPlanDelete) Where(ps ...predicate.CarpoolPlan) *CarpoolPlanDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CarpoolPlanDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CarpoolPlanDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CarpoolPlanDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(carpoolplan.Table, sqlgraph.NewFieldSpec(carpoolplan.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CarpoolPlanDeleteOne is the builder for deleting a single CarpoolPlan entity.
type CarpoolPlanDeleteOne struct {
	_d *CarpoolPlanDelete
}

// Where appends a list predicates to the CarpoolPlanDelete builder.
func (_d *CarpoolPlanDeleteOne) Where(ps ...predicate.CarpoolPlan) *CarpoolPlanDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CarpoolPlanDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{carpoolplan.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CarpoolPlanDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
