// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolplan"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CarpoolPlanUpdate is the builder for updating CarpoolPlan entities.
type CarpoolPlanUpdate struct {
	config
	hooks    []Hook
	mutation *CarpoolPlanMutation
}

// Where appends a list predicates to the CarpoolPlanUpdate builder.
func (_u *CarpoolPlanUpdate) Where(ps ...predicate.CarpoolPlan) *CarpoolPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *CarpoolPlanUpdate) SetTotalAmount(v float64) *CarpoolPlanUpdate {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *CarpoolPlanUpdate) SetNillableTotalAmount(v *float64) *CarpoolPlanUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *CarpoolPlanUpdate) AddTotalAmount(v float64) *CarpoolPlanUpdate {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetTargetMembers sets the "target_members" field.
func (_u *CarpoolPlanUpdate) SetTargetMembers(v int) *CarpoolPlanUpdate {
	_u.mutation.ResetTargetMembers()
	_u.mutation.SetTargetMembers(v)
	return _u
}

// SetNillableTargetMembers sets the "target_members" field if the given value is not nil.
func (_u *CarpoolPlanUpdate) SetNillableTargetMembers(v *int) *CarpoolPlanUpdate {
	if v != nil {
		_u.SetTargetMembers(*v)
	}
	return _u
}

// AddTargetMembers adds value to the "target_members" field.
func (_u *CarpoolPlanUpdate) AddTargetMembers(v int) *CarpoolPlanUpdate {
	_u.mutation.AddTargetMembers(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *CarpoolPlanUpdate) SetNote(v string) *CarpoolPlanUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *CarpoolPlanUpdate) SetNillableNote(v *string) *CarpoolPlanUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *CarpoolPlanUpdate) SetRevision(v int) *CarpoolPlanUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *CarpoolPlanUpdate) SetNillableRevision(v *int) *CarpoolPlanUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *CarpoolPlanUpdate) AddRevision(v int) *CarpoolPlanUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CarpoolPlanUpdate) SetUpdatedAt(v time.Time) *CarpoolPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CarpoolPlanMutation object of the builder.
func (_u *CarpoolPlanUpdate) Mutation() *CarpoolPlanMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CarpoolPlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CarpoolPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CarpoolPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CarpoolPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CarpoolPlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := carpoolplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CarpoolPlanUpdate) check() error {
	if v, ok := _u.mutation.Note(); ok {
		if err := carpoolplan.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "CarpoolPlan.note": %w`, err)}
		}
	}
	return nil
}

func (_u *CarpoolPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carpoolplan.Table, carpoolplan.Columns, sqlgraph.NewFieldSpec(carpoolplan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(carpoolplan.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(carpoolplan.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TargetMembers(); ok {
		_spec.SetField(carpoolplan.FieldTargetMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetMembers(); ok {
		_spec.AddField(carpoolplan.FieldTargetMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(carpoolplan.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(carpoolplan.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(carpoolplan.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carpoolplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CarpoolPlanUpdateOne is the builder for updating a single CarpoolPlan entity.
type CarpoolPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CarpoolPlanMutation
}

// SetTotalAmount sets the "total_amount" field.
func (_u *CarpoolPlanUpdateOne) SetTotalAmount(v float64) *CarpoolPlanUpdateOne {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *CarpoolPlanUpdateOne) SetNillableTotalAmount(v *float64) *CarpoolPlanUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *CarpoolPlanUpdateOne) AddTotalAmount(v float64) *CarpoolPlanUpdateOne {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetTargetMembers sets the "target_members" field.
func (_u *CarpoolPlanUpdateOne) SetTargetMembers(v int) *CarpoolPlanUpdateOne {
	_u.mutation.ResetTargetMembers()
	_u.mutation.SetTargetMembers(v)
	return _u
}

// SetNillableTargetMembers sets the "target_members" field if the given value is not nil.
func (_u *CarpoolPlanUpdateOne) SetNillableTargetMembers(v *int) *CarpoolPlanUpdateOne {
	if v != nil {
		_u.SetTargetMembers(*v)
	}
	return _u
}

// AddTargetMembers adds value to the "target_members" field.
func (_u *CarpoolPlanUpdateOne) AddTargetMembers(v int) *CarpoolPlanUpdateOne {
	_u.mutation.AddTargetMembers(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *CarpoolPlanUpdateOne) SetNote(v string) *CarpoolPlanUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *CarpoolPlanUpdateOne) SetNillableNote(v *string) *CarpoolPlanUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *CarpoolPlanUpdateOne) SetRevision(v int) *CarpoolPlanUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *CarpoolPlanUpdateOne) SetNillableRevision(v *int) *CarpoolPlanUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *CarpoolPlanUpdateOne) AddRevision(v int) *CarpoolPlanUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CarpoolPlanUpdateOne) SetUpdatedAt(v time.Time) *CarpoolPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CarpoolPlanMutation object of the builder.
func (_u *CarpoolPlanUpdateOne) Mutation() *CarpoolPlanMutation {
	return _u.mutation
}

// Where appends a list predicates to the CarpoolPlanUpdate builder.
func (_u *CarpoolPlanUpdateOne) Where(ps ...predicate.CarpoolPlan) *CarpoolPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CarpoolPlanUpdateOne) Select(field string, fields ...string) *CarpoolPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CarpoolPlan entity.
func (_u *CarpoolPlanUpdateOne) Save(ctx context.Context) (*CarpoolPlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CarpoolPlanUpdateOne) SaveX(ctx context.Context) *CarpoolPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CarpoolPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CarpoolPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CarpoolPlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := carpoolplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CarpoolPlanUpdateOne) check() error {
	if v, ok := _u.mutation.Note(); ok {
		if err := carpoolplan.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "CarpoolPlan.note": %w`, err)}
		}
	}
	return nil
}

func (_u *CarpoolPlanUpdateOne) sqlSave(ctx context.Context) (_node *CarpoolPlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carpoolplan.Table, carpoolplan.Columns, sqlgraph.NewFieldSpec(carpoolplan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CarpoolPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carpoolplan.FieldID)
		for _, f := range fields {
			if !carpoolplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != carpoolplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(carpoolplan.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(carpoolplan.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TargetMembers(); ok {
		_spec.SetField(carpoolplan.FieldTargetMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetMembers(); ok {
		_spec.AddField(carpoolplan.FieldTargetMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(carpoolplan.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(carpoolplan.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(carpoolplan.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolplan.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CarpoolPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carpoolplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
