// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/carpoolgroup"
)

// CarpoolGroup is the model entity for the CarpoolGroup schema.
type CarpoolGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CarpoolPlanID holds the value of the "carpool_plan_id" field.
	CarpoolPlanID int64 `json:"carpool_plan_id,omitempty"`
	// CarpoolPlanRevision holds the value of the "carpool_plan_revision" field.
	CarpoolPlanRevision int `json:"carpool_plan_revision,omitempty"`
	// TargetMembers holds the value of the "target_members" field.
	TargetMembers int `json:"target_members,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount float64 `json:"total_amount,omitempty"`
	// PricePerMember holds the value of the "price_per_member" field.
	PricePerMember float64 `json:"price_per_member,omitempty"`
	// PlanNote holds the value of the "plan_note" field.
	PlanNote string `json:"plan_note,omitempty"`
	// MemberCount holds the value of the "member_count" field.
	MemberCount int `json:"member_count,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// OpenKey holds the value of the "open_key" field.
	OpenKey *string `json:"open_key,omitempty"`
	// StatusReason holds the value of the "status_reason" field.
	StatusReason *string `json:"status_reason,omitempty"`
	// DeadlineAt holds the value of the "deadline_at" field.
	DeadlineAt *time.Time `json:"deadline_at,omitempty"`
	// FormedAt holds the value of the "formed_at" field.
	FormedAt *time.Time `json:"formed_at,omitempty"`
	// OpenedAt holds the value of the "opened_at" field.
	OpenedAt *time.Time `json:"opened_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CarpoolGroupQuery when eager-loading is set.
	Edges        CarpoolGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CarpoolGroupEdges holds the relations/edges for other nodes in the graph.
type CarpoolGroupEdges struct {
	// Orders holds the value of the orders edge.
	Orders []*PaymentOrder `json:"orders,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OrdersOrErr returns the Orders value or an error if the edge
// was not loaded in eager-loading.
func (e CarpoolGroupEdges) OrdersOrErr() ([]*PaymentOrder, error) {
	if e.loadedTypes[0] {
		return e.Orders, nil
	}
	return nil, &NotLoadedError{edge: "orders"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CarpoolGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case carpoolgroup.FieldTotalAmount, carpoolgroup.FieldPricePerMember:
			values[i] = new(sql.NullFloat64)
		case carpoolgroup.FieldID, carpoolgroup.FieldCarpoolPlanID, carpoolgroup.FieldCarpoolPlanRevision, carpoolgroup.FieldTargetMembers, carpoolgroup.FieldMemberCount:
			values[i] = new(sql.NullInt64)
		case carpoolgroup.FieldPlanNote, carpoolgroup.FieldStatus, carpoolgroup.FieldOpenKey, carpoolgroup.FieldStatusReason:
			values[i] = new(sql.NullString)
		case carpoolgroup.FieldDeadlineAt, carpoolgroup.FieldFormedAt, carpoolgroup.FieldOpenedAt, carpoolgroup.FieldExpiresAt, carpoolgroup.FieldCreatedAt, carpoolgroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CarpoolGroup fields.
func (_m *CarpoolGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case carpoolgroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case carpoolgroup.FieldCarpoolPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field carpool_plan_id", values[i])
			} else if value.Valid {
				_m.CarpoolPlanID = value.Int64
			}
		case carpoolgroup.FieldCarpoolPlanRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field carpool_plan_revision", values[i])
			} else if value.Valid {
				_m.CarpoolPlanRevision = int(value.Int64)
			}
		case carpoolgroup.FieldTargetMembers:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_members", values[i])
			} else if value.Valid {
				_m.TargetMembers = int(value.Int64)
			}
		case carpoolgroup.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.Float64
			}
		case carpoolgroup.FieldPricePerMember:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price_per_member", values[i])
			} else if value.Valid {
				_m.PricePerMember = value.Float64
			}
		case carpoolgroup.FieldPlanNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_note", values[i])
			} else if value.Valid {
				_m.PlanNote = value.String
			}
		case carpoolgroup.FieldMemberCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_count", values[i])
			} else if value.Valid {
				_m.MemberCount = int(value.Int64)
			}
		case carpoolgroup.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case carpoolgroup.FieldOpenKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field open_key", values[i])
			} else if value.Valid {
				_m.OpenKey = new(string)
				*_m.OpenKey = value.String
			}
		case carpoolgroup.FieldStatusReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status_reason", values[i])
			} else if value.Valid {
				_m.StatusReason = new(string)
				*_m.StatusReason = value.String
			}
		case carpoolgroup.FieldDeadlineAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deadline_at", values[i])
			} else if value.Valid {
				_m.DeadlineAt = new(time.Time)
				*_m.DeadlineAt = value.Time
			}
		case carpoolgroup.FieldFormedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field formed_at", values[i])
			} else if value.Valid {
				_m.FormedAt = new(time.Time)
				*_m.FormedAt = value.Time
			}
		case carpoolgroup.FieldOpenedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field opened_at", values[i])
			} else if value.Valid {
				_m.OpenedAt = new(time.Time)
				*_m.OpenedAt = value.Time
			}
		case carpoolgroup.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case carpoolgroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case carpoolgroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CarpoolGroup.
// This includes values selected through modifiers, order, etc.
func (_m *CarpoolGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrders queries the "orders" edge of the CarpoolGroup entity.
func (_m *CarpoolGroup) QueryOrders() *PaymentOrderQuery {
	return NewCarpoolGroupClient(_m.config).QueryOrders(_m)
}

// Update returns a builder for updating this CarpoolGroup.
// Note that you need to call CarpoolGroup.Unwrap() before calling this method if this CarpoolGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CarpoolGroup) Update() *CarpoolGroupUpdateOne {
	return NewCarpoolGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CarpoolGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CarpoolGroup) Unwrap() *CarpoolGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CarpoolGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CarpoolGroup) String() string {
	var builder strings.Builder
	builder.WriteString("CarpoolGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("carpool_plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CarpoolPlanID))
	builder.WriteString(", ")
	builder.WriteString("carpool_plan_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.CarpoolPlanRevision))
	builder.WriteString(", ")
	builder.WriteString("target_members=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetMembers))
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAmount))
	builder.WriteString(", ")
	builder.WriteString("price_per_member=")
	builder.WriteString(fmt.Sprintf("%v", _m.PricePerMember))
	builder.WriteString(", ")
	builder.WriteString("plan_note=")
	builder.WriteString(_m.PlanNote)
	builder.WriteString(", ")
	builder.WriteString("member_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemberCount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.OpenKey; v != nil {
		builder.WriteString("open_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.StatusReason; v != nil {
		builder.WriteString("status_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DeadlineAt; v != nil {
		builder.WriteString("deadline_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FormedAt; v != nil {
		builder.WriteString("formed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OpenedAt; v != nil {
		builder.WriteString("opened_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CarpoolGroups is a parsable slice of CarpoolGroup.
type CarpoolGroups []*CarpoolGroup
