// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolgroup"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
)

// CarpoolGroupCreate is the builder for creating a CarpoolGroup entity.
type CarpoolGroupCreate struct {
	config
	mutation *CarpoolGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCarpoolPlanID sets the "carpool_plan_id" field.
func (_c *CarpoolGroupCreate) SetCarpoolPlanID(v int64) *CarpoolGroupCreate {
	_c.mutation.SetCarpoolPlanID(v)
	return _c
}

// SetCarpoolPlanRevision sets the "carpool_plan_revision" field.
func (_c *CarpoolGroupCreate) SetCarpoolPlanRevision(v int) *CarpoolGroupCreate {
	_c.mutation.SetCarpoolPlanRevision(v)
	return _c
}

// SetTargetMembers sets the "target_members" field.
func (_c *CarpoolGroupCreate) SetTargetMembers(v int) *CarpoolGroupCreate {
	_c.mutation.SetTargetMembers(v)
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *CarpoolGroupCreate) SetTotalAmount(v float64) *CarpoolGroupCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetPricePerMember sets the "price_per_member" field.
func (_c *CarpoolGroupCreate) SetPricePerMember(v float64) *CarpoolGroupCreate {
	_c.mutation.SetPricePerMember(v)
	return _c
}

// SetPlanNote sets the "plan_note" field.
func (_c *CarpoolGroupCreate) SetPlanNote(v string) *CarpoolGroupCreate {
	_c.mutation.SetPlanNote(v)
	return _c
}

// SetMemberCount sets the "member_count" field.
func (_c *CarpoolGroupCreate) SetMemberCount(v int) *CarpoolGroupCreate {
	_c.mutation.SetMemberCount(v)
	return _c
}

// SetNillableMemberCount sets the "member_count" field if the given value is not nil.
func (_c *CarpoolGroupCreate) SetNillableMemberCount(v *int) *CarpoolGroupCreate {
	if v != nil {
		_c.SetMemberCount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CarpoolGroupCreate) SetStatus(v string) *CarpoolGroupCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetOpenKey sets the "open_key" field.
func (_c *CarpoolGroupCreate) SetOpenKey(v string) *CarpoolGroupCreate {
	_c.mutation.SetOpenKey(v)
	return _c
}

// SetNillableOpenKey sets the "open_key" field if the given value is not nil.
func (_c *CarpoolGroupCreate) SetNillableOpenKey(v *string) *CarpoolGroupCreate {
	if v != nil {
		_c.SetOpenKey(*v)
	}
	return _c
}

// SetStatusReason sets the "status_reason" field.
func (_c *CarpoolGroupCreate) SetStatusReason(v string) *CarpoolGroupCreate {
	_c.mutation.SetStatusReason(v)
	return _c
}

// SetNillableStatusReason sets the "status_reason" field if the given value is not nil.
func (_c *CarpoolGroupCreate) SetNillableStatusReason(v *string) *CarpoolGroupCreate {
	if v != nil {
		_c.SetStatusReason(*v)
	}
	return _c
}

// SetDeadlineAt sets the "deadline_at" field.
func (_c *CarpoolGroupCreate) SetDeadlineAt(v time.Time) *CarpoolGroupCreate {
	_c.mutation.SetDeadlineAt(v)
	return _c
}

// SetNillableDeadlineAt sets the "deadline_at" field if the given value is not nil.
func (_c *CarpoolGroupCreate) SetNillableDeadlineAt(v *time.Time) *CarpoolGroupCreate {
	if v != nil {
		_c.SetDeadlineAt(*v)
	}
	return _c
}

// SetFormedAt sets the "formed_at" field.
func (_c *CarpoolGroupCreate) SetFormedAt(v time.Time) *CarpoolGroupCreate {
	_c.mutation.SetFormedAt(v)
	return _c
}

// SetNillableFormedAt sets the "formed_at" field if the given value is not nil.
func (_c *CarpoolGroupCreate) SetNillableFormedAt(v *time.Time) *CarpoolGroupCreate {
	if v != nil {
		_c.SetFormedAt(*v)
	}
	return _c
}

// SetOpenedAt sets the "opened_at" field.
func (_c *CarpoolGroupCreate) SetOpenedAt(v time.Time) *CarpoolGroupCreate {
	_c.mutation.SetOpenedAt(v)
	return _c
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_c *CarpoolGroupCreate) SetNillableOpenedAt(v *time.Time) *CarpoolGroupCreate {
	if v != nil {
		_c.SetOpenedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CarpoolGroupCreate) SetExpiresAt(v time.Time) *CarpoolGroupCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *CarpoolGroupCreate) SetNillableExpiresAt(v *time.Time) *CarpoolGroupCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CarpoolGroupCreate) SetCreatedAt(v time.Time) *CarpoolGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CarpoolGroupCreate) SetNillableCreatedAt(v *time.Time) *CarpoolGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CarpoolGroupCreate) SetUpdatedAt(v time.Time) *CarpoolGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CarpoolGroupCreate) SetNillableUpdatedAt(v *time.Time) *CarpoolGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddOrderIDs adds the "orders" edge to the PaymentOrder entity by IDs.
func (_c *CarpoolGroupCreate) AddOrderIDs(ids ...int64) *CarpoolGroupCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the PaymentOrder entity.
func (_c *CarpoolGroupCreate) AddOrders(v ...*PaymentOrder) *CarpoolGroupCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// Mutation returns the CarpoolGroupMutation object of the builder.
func (_c *CarpoolGroupCreate) Mutation() *CarpoolGroupMutation {
	return _c.mutation
}

// Save creates the CarpoolGroup in the database.
func (_c *CarpoolGroupCreate) Save(ctx context.Context) (*CarpoolGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CarpoolGroupCreate) SaveX(ctx context.Context) *CarpoolGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CarpoolGroupCreate) defaults() {
	if _, ok := _c.mutation.MemberCount(); !ok {
		v := carpoolgroup.DefaultMemberCount
		_c.mutation.SetMemberCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := carpoolgroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := carpoolgroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CarpoolGroupCreate) check() error {
	if _, ok := _c.mutation.CarpoolPlanID(); !ok {
		return &ValidationError{Name: "carpool_plan_id", err: errors.New(`ent: missing required field "CarpoolGroup.carpool_plan_id"`)}
	}
	if _, ok := _c.mutation.CarpoolPlanRevision(); !ok {
		return &ValidationError{Name: "carpool_plan_revision", err: errors.New(`ent: missing required field "CarpoolGroup.carpool_plan_revision"`)}
	}
	if _, ok := _c.mutation.TargetMembers(); !ok {
		return &ValidationError{Name: "target_members", err: errors.New(`ent: missing required field "CarpoolGroup.target_members"`)}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "CarpoolGroup.total_amount"`)}
	}
	if _, ok := _c.mutation.PricePerMember(); !ok {
		return &ValidationError{Name: "price_per_member", err: errors.New(`ent: missing required field "CarpoolGroup.price_per_member"`)}
	}
	if _, ok := _c.mutation.PlanNote(); !ok {
		return &ValidationError{Name: "plan_note", err: errors.New(`ent: missing required field "CarpoolGroup.plan_note"`)}
	}
	if _, ok := _c.mutation.MemberCount(); !ok {
		return &ValidationError{Name: "member_count", err: errors.New(`ent: missing required field "CarpoolGroup.member_count"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CarpoolGroup.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := carpoolgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CarpoolGroup.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OpenKey(); ok {
		if err := carpoolgroup.OpenKeyValidator(v); err != nil {
			return &ValidationError{Name: "open_key", err: fmt.Errorf(`ent: validator failed for field "CarpoolGroup.open_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CarpoolGroup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CarpoolGroup.updated_at"`)}
	}
	return nil
}

func (_c *CarpoolGroupCreate) sqlSave(ctx context.Context) (*CarpoolGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CarpoolGroupCreate) createSpec() (*CarpoolGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &CarpoolGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(carpoolgroup.Table, sqlgraph.NewFieldSpec(carpoolgroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CarpoolPlanID(); ok {
		_spec.SetField(carpoolgroup.FieldCarpoolPlanID, field.TypeInt64, value)
		_node.CarpoolPlanID = value
	}
	if value, ok := _c.mutation.CarpoolPlanRevision(); ok {
		_spec.SetField(carpoolgroup.FieldCarpoolPlanRevision, field.TypeInt, value)
		_node.CarpoolPlanRevision = value
	}
	if value, ok := _c.mutation.TargetMembers(); ok {
		_spec.SetField(carpoolgroup.FieldTargetMembers, field.TypeInt, value)
		_node.TargetMembers = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(carpoolgroup.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.PricePerMember(); ok {
		_spec.SetField(carpoolgroup.FieldPricePerMember, field.TypeFloat64, value)
		_node.PricePerMember = value
	}
	if value, ok := _c.mutation.PlanNote(); ok {
		_spec.SetField(carpoolgroup.FieldPlanNote, field.TypeString, value)
		_node.PlanNote = value
	}
	if value, ok := _c.mutation.MemberCount(); ok {
		_spec.SetField(carpoolgroup.FieldMemberCount, field.TypeInt, value)
		_node.MemberCount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(carpoolgroup.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.OpenKey(); ok {
		_spec.SetField(carpoolgroup.FieldOpenKey, field.TypeString, value)
		_node.OpenKey = &value
	}
	if value, ok := _c.mutation.StatusReason(); ok {
		_spec.SetField(carpoolgroup.FieldStatusReason, field.TypeString, value)
		_node.StatusReason = &value
	}
	if value, ok := _c.mutation.DeadlineAt(); ok {
		_spec.SetField(carpoolgroup.FieldDeadlineAt, field.TypeTime, value)
		_node.DeadlineAt = &value
	}
	if value, ok := _c.mutation.FormedAt(); ok {
		_spec.SetField(carpoolgroup.FieldFormedAt, field.TypeTime, value)
		_node.FormedAt = &value
	}
	if value, ok := _c.mutation.OpenedAt(); ok {
		_spec.SetField(carpoolgroup.FieldOpenedAt, field.TypeTime, value)
		_node.OpenedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(carpoolgroup.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(carpoolgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolgroup.OrdersTable,
			Columns: []string{carpoolgroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolGroup.Create().
//		SetCarpoolPlanID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolGroupUpsert) {
//			SetCarpoolPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolGroupCreate) OnConflict(opts ...sql.ConflictOption) *CarpoolGroupUpsertOne {
	_c.conflict = opts
	return &CarpoolGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolGroupCreate) OnConflictColumns(columns ...string) *CarpoolGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolGroupUpsertOne{
		create: _c,
	}
}

type (
	// CarpoolGroupUpsertOne is the builder for "upsert"-ing
	//  one CarpoolGroup node.
	CarpoolGroupUpsertOne struct {
		create *CarpoolGroupCreate
	}

	// CarpoolGroupUpsert is the "OnConflict" setter.
	CarpoolGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetCarpoolPlanID sets the "carpool_plan_id" field.
func (u *CarpoolGroupUpsert) SetCarpoolPlanID(v int64) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldCarpoolPlanID, v)
	return u
}

// UpdateCarpoolPlanID sets the "carpool_plan_id" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateCarpoolPlanID() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldCarpoolPlanID)
	return u
}

// AddCarpoolPlanID adds v to the "carpool_plan_id" field.
func (u *CarpoolGroupUpsert) AddCarpoolPlanID(v int64) *CarpoolGroupUpsert {
	u.Add(carpoolgroup.FieldCarpoolPlanID, v)
	return u
}

// SetCarpoolPlanRevision sets the "carpool_plan_revision" field.
func (u *CarpoolGroupUpsert) SetCarpoolPlanRevision(v int) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldCarpoolPlanRevision, v)
	return u
}

// UpdateCarpoolPlanRevision sets the "carpool_plan_revision" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateCarpoolPlanRevision() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldCarpoolPlanRevision)
	return u
}

// AddCarpoolPlanRevision adds v to the "carpool_plan_revision" field.
func (u *CarpoolGroupUpsert) AddCarpoolPlanRevision(v int) *CarpoolGroupUpsert {
	u.Add(carpoolgroup.FieldCarpoolPlanRevision, v)
	return u
}

// SetTargetMembers sets the "target_members" field.
func (u *CarpoolGroupUpsert) SetTargetMembers(v int) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldTargetMembers, v)
	return u
}

// UpdateTargetMembers sets the "target_members" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateTargetMembers() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldTargetMembers)
	return u
}

// AddTargetMembers adds v to the "target_members" field.
func (u *CarpoolGroupUpsert) AddTargetMembers(v int) *CarpoolGroupUpsert {
	u.Add(carpoolgroup.FieldTargetMembers, v)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *CarpoolGroupUpsert) SetTotalAmount(v float64) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateTotalAmount() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *CarpoolGroupUpsert) AddTotalAmount(v float64) *CarpoolGroupUpsert {
	u.Add(carpoolgroup.FieldTotalAmount, v)
	return u
}

// SetPricePerMember sets the "price_per_member" field.
func (u *CarpoolGroupUpsert) SetPricePerMember(v float64) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldPricePerMember, v)
	return u
}

// UpdatePricePerMember sets the "price_per_member" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdatePricePerMember() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldPricePerMember)
	return u
}

// AddPricePerMember adds v to the "price_per_member" field.
func (u *CarpoolGroupUpsert) AddPricePerMember(v float64) *CarpoolGroupUpsert {
	u.Add(carpoolgroup.FieldPricePerMember, v)
	return u
}

// SetPlanNote sets the "plan_note" field.
func (u *CarpoolGroupUpsert) SetPlanNote(v string) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldPlanNote, v)
	return u
}

// UpdatePlanNote sets the "plan_note" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdatePlanNote() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldPlanNote)
	return u
}

// SetMemberCount sets the "member_count" field.
func (u *CarpoolGroupUpsert) SetMemberCount(v int) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldMemberCount, v)
	return u
}

// UpdateMemberCount sets the "member_count" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateMemberCount() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldMemberCount)
	return u
}

// AddMemberCount adds v to the "member_count" field.
func (u *CarpoolGroupUpsert) AddMemberCount(v int) *CarpoolGroupUpsert {
	u.Add(carpoolgroup.FieldMemberCount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *CarpoolGroupUpsert) SetStatus(v string) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateStatus() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldStatus)
	return u
}

// SetOpenKey sets the "open_key" field.
func (u *CarpoolGroupUpsert) SetOpenKey(v string) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldOpenKey, v)
	return u
}

// UpdateOpenKey sets the "open_key" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateOpenKey() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldOpenKey)
	return u
}

// ClearOpenKey clears the value of the "open_key" field.
func (u *CarpoolGroupUpsert) ClearOpenKey() *CarpoolGroupUpsert {
	u.SetNull(carpoolgroup.FieldOpenKey)
	return u
}

// SetStatusReason sets the "status_reason" field.
func (u *CarpoolGroupUpsert) SetStatusReason(v string) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldStatusReason, v)
	return u
}

// UpdateStatusReason sets the "status_reason" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateStatusReason() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldStatusReason)
	return u
}

// ClearStatusReason clears the value of the "status_reason" field.
func (u *CarpoolGroupUpsert) ClearStatusReason() *CarpoolGroupUpsert {
	u.SetNull(carpoolgroup.FieldStatusReason)
	return u
}

// SetDeadlineAt sets the "deadline_at" field.
func (u *CarpoolGroupUpsert) SetDeadlineAt(v time.Time) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldDeadlineAt, v)
	return u
}

// UpdateDeadlineAt sets the "deadline_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateDeadlineAt() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldDeadlineAt)
	return u
}

// ClearDeadlineAt clears the value of the "deadline_at" field.
func (u *CarpoolGroupUpsert) ClearDeadlineAt() *CarpoolGroupUpsert {
	u.SetNull(carpoolgroup.FieldDeadlineAt)
	return u
}

// SetFormedAt sets the "formed_at" field.
func (u *CarpoolGroupUpsert) SetFormedAt(v time.Time) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldFormedAt, v)
	return u
}

// UpdateFormedAt sets the "formed_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateFormedAt() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldFormedAt)
	return u
}

// ClearFormedAt clears the value of the "formed_at" field.
func (u *CarpoolGroupUpsert) ClearFormedAt() *CarpoolGroupUpsert {
	u.SetNull(carpoolgroup.FieldFormedAt)
	return u
}

// SetOpenedAt sets the "opened_at" field.
func (u *CarpoolGroupUpsert) SetOpenedAt(v time.Time) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldOpenedAt, v)
	return u
}

// UpdateOpenedAt sets the "opened_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateOpenedAt() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldOpenedAt)
	return u
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (u *CarpoolGroupUpsert) ClearOpenedAt() *CarpoolGroupUpsert {
	u.SetNull(carpoolgroup.FieldOpenedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *CarpoolGroupUpsert) SetExpiresAt(v time.Time) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateExpiresAt() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *CarpoolGroupUpsert) ClearExpiresAt() *CarpoolGroupUpsert {
	u.SetNull(carpoolgroup.FieldExpiresAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolGroupUpsert) SetUpdatedAt(v time.Time) *CarpoolGroupUpsert {
	u.Set(carpoolgroup.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsert) UpdateUpdatedAt() *CarpoolGroupUpsert {
	u.SetExcluded(carpoolgroup.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CarpoolGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolGroupUpsertOne) UpdateNewValues() *CarpoolGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(carpoolgroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CarpoolGroupUpsertOne) Ignore() *CarpoolGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolGroupUpsertOne) DoNothing() *CarpoolGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolGroupCreate.OnConflict
// documentation for more info.
func (u *CarpoolGroupUpsertOne) Update(set func(*CarpoolGroupUpsert)) *CarpoolGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetCarpoolPlanID sets the "carpool_plan_id" field.
func (u *CarpoolGroupUpsertOne) SetCarpoolPlanID(v int64) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetCarpoolPlanID(v)
	})
}

// AddCarpoolPlanID adds v to the "carpool_plan_id" field.
func (u *CarpoolGroupUpsertOne) AddCarpoolPlanID(v int64) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddCarpoolPlanID(v)
	})
}

// UpdateCarpoolPlanID sets the "carpool_plan_id" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateCarpoolPlanID() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateCarpoolPlanID()
	})
}

// SetCarpoolPlanRevision sets the "carpool_plan_revision" field.
func (u *CarpoolGroupUpsertOne) SetCarpoolPlanRevision(v int) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetCarpoolPlanRevision(v)
	})
}

// AddCarpoolPlanRevision adds v to the "carpool_plan_revision" field.
func (u *CarpoolGroupUpsertOne) AddCarpoolPlanRevision(v int) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddCarpoolPlanRevision(v)
	})
}

// UpdateCarpoolPlanRevision sets the "carpool_plan_revision" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateCarpoolPlanRevision() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateCarpoolPlanRevision()
	})
}

// SetTargetMembers sets the "target_members" field.
func (u *CarpoolGroupUpsertOne) SetTargetMembers(v int) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetTargetMembers(v)
	})
}

// AddTargetMembers adds v to the "target_members" field.
func (u *CarpoolGroupUpsertOne) AddTargetMembers(v int) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddTargetMembers(v)
	})
}

// UpdateTargetMembers sets the "target_members" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateTargetMembers() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateTargetMembers()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *CarpoolGroupUpsertOne) SetTotalAmount(v float64) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *CarpoolGroupUpsertOne) AddTotalAmount(v float64) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateTotalAmount() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetPricePerMember sets the "price_per_member" field.
func (u *CarpoolGroupUpsertOne) SetPricePerMember(v float64) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetPricePerMember(v)
	})
}

// AddPricePerMember adds v to the "price_per_member" field.
func (u *CarpoolGroupUpsertOne) AddPricePerMember(v float64) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddPricePerMember(v)
	})
}

// UpdatePricePerMember sets the "price_per_member" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdatePricePerMember() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdatePricePerMember()
	})
}

// SetPlanNote sets the "plan_note" field.
func (u *CarpoolGroupUpsertOne) SetPlanNote(v string) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetPlanNote(v)
	})
}

// UpdatePlanNote sets the "plan_note" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdatePlanNote() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdatePlanNote()
	})
}

// SetMemberCount sets the "member_count" field.
func (u *CarpoolGroupUpsertOne) SetMemberCount(v int) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetMemberCount(v)
	})
}

// AddMemberCount adds v to the "member_count" field.
func (u *CarpoolGroupUpsertOne) AddMemberCount(v int) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddMemberCount(v)
	})
}

// UpdateMemberCount sets the "member_count" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateMemberCount() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateMemberCount()
	})
}

// SetStatus sets the "status" field.
func (u *CarpoolGroupUpsertOne) SetStatus(v string) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateStatus() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateStatus()
	})
}

// SetOpenKey sets the "open_key" field.
func (u *CarpoolGroupUpsertOne) SetOpenKey(v string) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetOpenKey(v)
	})
}

// UpdateOpenKey sets the "open_key" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateOpenKey() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateOpenKey()
	})
}

// ClearOpenKey clears the value of the "open_key" field.
func (u *CarpoolGroupUpsertOne) ClearOpenKey() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearOpenKey()
	})
}

// SetStatusReason sets the "status_reason" field.
func (u *CarpoolGroupUpsertOne) SetStatusReason(v string) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetStatusReason(v)
	})
}

// UpdateStatusReason sets the "status_reason" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateStatusReason() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateStatusReason()
	})
}

// ClearStatusReason clears the value of the "status_reason" field.
func (u *CarpoolGroupUpsertOne) ClearStatusReason() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearStatusReason()
	})
}

// SetDeadlineAt sets the "deadline_at" field.
func (u *CarpoolGroupUpsertOne) SetDeadlineAt(v time.Time) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetDeadlineAt(v)
	})
}

// UpdateDeadlineAt sets the "deadline_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateDeadlineAt() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateDeadlineAt()
	})
}

// ClearDeadlineAt clears the value of the "deadline_at" field.
func (u *CarpoolGroupUpsertOne) ClearDeadlineAt() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearDeadlineAt()
	})
}

// SetFormedAt sets the "formed_at" field.
func (u *CarpoolGroupUpsertOne) SetFormedAt(v time.Time) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetFormedAt(v)
	})
}

// UpdateFormedAt sets the "formed_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateFormedAt() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateFormedAt()
	})
}

// ClearFormedAt clears the value of the "formed_at" field.
func (u *CarpoolGroupUpsertOne) ClearFormedAt() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearFormedAt()
	})
}

// SetOpenedAt sets the "opened_at" field.
func (u *CarpoolGroupUpsertOne) SetOpenedAt(v time.Time) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetOpenedAt(v)
	})
}

// UpdateOpenedAt sets the "opened_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateOpenedAt() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateOpenedAt()
	})
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (u *CarpoolGroupUpsertOne) ClearOpenedAt() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearOpenedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CarpoolGroupUpsertOne) SetExpiresAt(v time.Time) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateExpiresAt() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *CarpoolGroupUpsertOne) ClearExpiresAt() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolGroupUpsertOne) SetUpdatedAt(v time.Time) *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsertOne) UpdateUpdatedAt() *CarpoolGroupUpsertOne {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CarpoolGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CarpoolGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CarpoolGroupCreateBulk is the builder for creating many CarpoolGroup entities in bulk.
type CarpoolGroupCreateBulk struct {
	config
	err      error
	builders []*CarpoolGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the CarpoolGroup entities in the database.
func (_c *CarpoolGroupCreateBulk) Save(ctx context.Context) ([]*CarpoolGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CarpoolGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarpoolGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CarpoolGroupCreateBulk) SaveX(ctx context.Context) []*CarpoolGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolGroupUpsert) {
//			SetCarpoolPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *CarpoolGroupUpsertBulk {
	_c.conflict = opts
	return &CarpoolGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolGroupCreateBulk) OnConflictColumns(columns ...string) *CarpoolGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolGroupUpsertBulk{
		create: _c,
	}
}

// CarpoolGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of CarpoolGroup nodes.
type CarpoolGroupUpsertBulk struct {
	create *CarpoolGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CarpoolGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolGroupUpsertBulk) UpdateNewValues() *CarpoolGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(carpoolgroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CarpoolGroupUpsertBulk) Ignore() *CarpoolGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolGroupUpsertBulk) DoNothing() *CarpoolGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolGroupCreateBulk.OnConflict
// documentation for more info.
func (u *CarpoolGroupUpsertBulk) Update(set func(*CarpoolGroupUpsert)) *CarpoolGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetCarpoolPlanID sets the "carpool_plan_id" field.
func (u *CarpoolGroupUpsertBulk) SetCarpoolPlanID(v int64) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetCarpoolPlanID(v)
	})
}

// AddCarpoolPlanID adds v to the "carpool_plan_id" field.
func (u *CarpoolGroupUpsertBulk) AddCarpoolPlanID(v int64) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddCarpoolPlanID(v)
	})
}

// UpdateCarpoolPlanID sets the "carpool_plan_id" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateCarpoolPlanID() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateCarpoolPlanID()
	})
}

// SetCarpoolPlanRevision sets the "carpool_plan_revision" field.
func (u *CarpoolGroupUpsertBulk) SetCarpoolPlanRevision(v int) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetCarpoolPlanRevision(v)
	})
}

// AddCarpoolPlanRevision adds v to the "carpool_plan_revision" field.
func (u *CarpoolGroupUpsertBulk) AddCarpoolPlanRevision(v int) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddCarpoolPlanRevision(v)
	})
}

// UpdateCarpoolPlanRevision sets the "carpool_plan_revision" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateCarpoolPlanRevision() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateCarpoolPlanRevision()
	})
}

// SetTargetMembers sets the "target_members" field.
func (u *CarpoolGroupUpsertBulk) SetTargetMembers(v int) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetTargetMembers(v)
	})
}

// AddTargetMembers adds v to the "target_members" field.
func (u *CarpoolGroupUpsertBulk) AddTargetMembers(v int) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddTargetMembers(v)
	})
}

// UpdateTargetMembers sets the "target_members" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateTargetMembers() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateTargetMembers()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *CarpoolGroupUpsertBulk) SetTotalAmount(v float64) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *CarpoolGroupUpsertBulk) AddTotalAmount(v float64) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateTotalAmount() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetPricePerMember sets the "price_per_member" field.
func (u *CarpoolGroupUpsertBulk) SetPricePerMember(v float64) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetPricePerMember(v)
	})
}

// AddPricePerMember adds v to the "price_per_member" field.
func (u *CarpoolGroupUpsertBulk) AddPricePerMember(v float64) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddPricePerMember(v)
	})
}

// UpdatePricePerMember sets the "price_per_member" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdatePricePerMember() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdatePricePerMember()
	})
}

// SetPlanNote sets the "plan_note" field.
func (u *CarpoolGroupUpsertBulk) SetPlanNote(v string) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetPlanNote(v)
	})
}

// UpdatePlanNote sets the "plan_note" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdatePlanNote() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdatePlanNote()
	})
}

// SetMemberCount sets the "member_count" field.
func (u *CarpoolGroupUpsertBulk) SetMemberCount(v int) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetMemberCount(v)
	})
}

// AddMemberCount adds v to the "member_count" field.
func (u *CarpoolGroupUpsertBulk) AddMemberCount(v int) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.AddMemberCount(v)
	})
}

// UpdateMemberCount sets the "member_count" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateMemberCount() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateMemberCount()
	})
}

// SetStatus sets the "status" field.
func (u *CarpoolGroupUpsertBulk) SetStatus(v string) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateStatus() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateStatus()
	})
}

// SetOpenKey sets the "open_key" field.
func (u *CarpoolGroupUpsertBulk) SetOpenKey(v string) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetOpenKey(v)
	})
}

// UpdateOpenKey sets the "open_key" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateOpenKey() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateOpenKey()
	})
}

// ClearOpenKey clears the value of the "open_key" field.
func (u *CarpoolGroupUpsertBulk) ClearOpenKey() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearOpenKey()
	})
}

// SetStatusReason sets the "status_reason" field.
func (u *CarpoolGroupUpsertBulk) SetStatusReason(v string) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetStatusReason(v)
	})
}

// UpdateStatusReason sets the "status_reason" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateStatusReason() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateStatusReason()
	})
}

// ClearStatusReason clears the value of the "status_reason" field.
func (u *CarpoolGroupUpsertBulk) ClearStatusReason() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearStatusReason()
	})
}

// SetDeadlineAt sets the "deadline_at" field.
func (u *CarpoolGroupUpsertBulk) SetDeadlineAt(v time.Time) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetDeadlineAt(v)
	})
}

// UpdateDeadlineAt sets the "deadline_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateDeadlineAt() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateDeadlineAt()
	})
}

// ClearDeadlineAt clears the value of the "deadline_at" field.
func (u *CarpoolGroupUpsertBulk) ClearDeadlineAt() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearDeadlineAt()
	})
}

// SetFormedAt sets the "formed_at" field.
func (u *CarpoolGroupUpsertBulk) SetFormedAt(v time.Time) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetFormedAt(v)
	})
}

// UpdateFormedAt sets the "formed_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateFormedAt() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateFormedAt()
	})
}

// ClearFormedAt clears the value of the "formed_at" field.
func (u *CarpoolGroupUpsertBulk) ClearFormedAt() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearFormedAt()
	})
}

// SetOpenedAt sets the "opened_at" field.
func (u *CarpoolGroupUpsertBulk) SetOpenedAt(v time.Time) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetOpenedAt(v)
	})
}

// UpdateOpenedAt sets the "opened_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateOpenedAt() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateOpenedAt()
	})
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (u *CarpoolGroupUpsertBulk) ClearOpenedAt() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearOpenedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CarpoolGroupUpsertBulk) SetExpiresAt(v time.Time) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateExpiresAt() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *CarpoolGroupUpsertBulk) ClearExpiresAt() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.ClearExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolGroupUpsertBulk) SetUpdatedAt(v time.Time) *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolGroupUpsertBulk) UpdateUpdatedAt() *CarpoolGroupUpsertBulk {
	return u.Update(func(s *CarpoolGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CarpoolGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
