// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/rechargelotterydraw"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RechargeLotteryDrawCreate is the builder for creating a RechargeLotteryDraw entity.
type RechargeLotteryDrawCreate struct {
	config
	mutation *RechargeLotteryDrawMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *RechargeLotteryDrawCreate) SetUserID(v int64) *RechargeLotteryDrawCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *RechargeLotteryDrawCreate) SetOrderID(v int64) *RechargeLotteryDrawCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetRechargeAmount sets the "recharge_amount" field.
func (_c *RechargeLotteryDrawCreate) SetRechargeAmount(v float64) *RechargeLotteryDrawCreate {
	_c.mutation.SetRechargeAmount(v)
	return _c
}

// SetMaxRarity sets the "max_rarity" field.
func (_c *RechargeLotteryDrawCreate) SetMaxRarity(v string) *RechargeLotteryDrawCreate {
	_c.mutation.SetMaxRarity(v)
	return _c
}

// SetRarity sets the "rarity" field.
func (_c *RechargeLotteryDrawCreate) SetRarity(v string) *RechargeLotteryDrawCreate {
	_c.mutation.SetRarity(v)
	return _c
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_c *RechargeLotteryDrawCreate) SetNillableRarity(v *string) *RechargeLotteryDrawCreate {
	if v != nil {
		_c.SetRarity(*v)
	}
	return _c
}

// SetRewardAmount sets the "reward_amount" field.
func (_c *RechargeLotteryDrawCreate) SetRewardAmount(v float64) *RechargeLotteryDrawCreate {
	_c.mutation.SetRewardAmount(v)
	return _c
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_c *RechargeLotteryDrawCreate) SetNillableRewardAmount(v *float64) *RechargeLotteryDrawCreate {
	if v != nil {
		_c.SetRewardAmount(*v)
	}
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *RechargeLotteryDrawCreate) SetBalanceAfter(v float64) *RechargeLotteryDrawCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_c *RechargeLotteryDrawCreate) SetNillableBalanceAfter(v *float64) *RechargeLotteryDrawCreate {
	if v != nil {
		_c.SetBalanceAfter(*v)
	}
	return _c
}

// SetClaimedAt sets the "claimed_at" field.
func (_c *RechargeLotteryDrawCreate) SetClaimedAt(v time.Time) *RechargeLotteryDrawCreate {
	_c.mutation.SetClaimedAt(v)
	return _c
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_c *RechargeLotteryDrawCreate) SetNillableClaimedAt(v *time.Time) *RechargeLotteryDrawCreate {
	if v != nil {
		_c.SetClaimedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RechargeLotteryDrawCreate) SetCreatedAt(v time.Time) *RechargeLotteryDrawCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RechargeLotteryDrawCreate) SetNillableCreatedAt(v *time.Time) *RechargeLotteryDrawCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RechargeLotteryDrawCreate) SetUser(v *User) *RechargeLotteryDrawCreate {
	return _c.SetUserID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_c *RechargeLotteryDrawCreate) SetOrder(v *PaymentOrder) *RechargeLotteryDrawCreate {
	return _c.SetOrderID(v.ID)
}

// Mutation returns the RechargeLotteryDrawMutation object of the builder.
func (_c *RechargeLotteryDrawCreate) Mutation() *RechargeLotteryDrawMutation {
	return _c.mutation
}

// Save creates the RechargeLotteryDraw in the database.
func (_c *RechargeLotteryDrawCreate) Save(ctx context.Context) (*RechargeLotteryDraw, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RechargeLotteryDrawCreate) SaveX(ctx context.Context) *RechargeLotteryDraw {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeLotteryDrawCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeLotteryDrawCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RechargeLotteryDrawCreate) defaults() {
	if _, ok := _c.mutation.Rarity(); !ok {
		v := rechargelotterydraw.DefaultRarity
		_c.mutation.SetRarity(v)
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		v := rechargelotterydraw.DefaultRewardAmount
		_c.mutation.SetRewardAmount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rechargelotterydraw.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RechargeLotteryDrawCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RechargeLotteryDraw.user_id"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "RechargeLotteryDraw.order_id"`)}
	}
	if _, ok := _c.mutation.RechargeAmount(); !ok {
		return &ValidationError{Name: "recharge_amount", err: errors.New(`ent: missing required field "RechargeLotteryDraw.recharge_amount"`)}
	}
	if _, ok := _c.mutation.MaxRarity(); !ok {
		return &ValidationError{Name: "max_rarity", err: errors.New(`ent: missing required field "RechargeLotteryDraw.max_rarity"`)}
	}
	if v, ok := _c.mutation.MaxRarity(); ok {
		if err := rechargelotterydraw.MaxRarityValidator(v); err != nil {
			return &ValidationError{Name: "max_rarity", err: fmt.Errorf(`ent: validator failed for field "RechargeLotteryDraw.max_rarity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rarity(); !ok {
		return &ValidationError{Name: "rarity", err: errors.New(`ent: missing required field "RechargeLotteryDraw.rarity"`)}
	}
	if v, ok := _c.mutation.Rarity(); ok {
		if err := rechargelotterydraw.RarityValidator(v); err != nil {
			return &ValidationError{Name: "rarity", err: fmt.Errorf(`ent: validator failed for field "RechargeLotteryDraw.rarity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		return &ValidationError{Name: "reward_amount", err: errors.New(`ent: missing required field "RechargeLotteryDraw.reward_amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RechargeLotteryDraw.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RechargeLotteryDraw.user"`)}
	}
	if len(_c.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "RechargeLotteryDraw.order"`)}
	}
	return nil
}

func (_c *RechargeLotteryDrawCreate) sqlSave(ctx context.Context) (*RechargeLotteryDraw, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RechargeLotteryDrawCreate) createSpec() (*RechargeLotteryDraw, *sqlgraph.CreateSpec) {
	var (
		_node = &RechargeLotteryDraw{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rechargelotterydraw.Table, sqlgraph.NewFieldSpec(rechargelotterydraw.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RechargeAmount(); ok {
		_spec.SetField(rechargelotterydraw.FieldRechargeAmount, field.TypeFloat64, value)
		_node.RechargeAmount = value
	}
	if value, ok := _c.mutation.MaxRarity(); ok {
		_spec.SetField(rechargelotterydraw.FieldMaxRarity, field.TypeString, value)
		_node.MaxRarity = value
	}
	if value, ok := _c.mutation.Rarity(); ok {
		_spec.SetField(rechargelotterydraw.FieldRarity, field.TypeString, value)
		_node.Rarity = value
	}
	if value, ok := _c.mutation.RewardAmount(); ok {
		_spec.SetField(rechargelotterydraw.FieldRewardAmount, field.TypeFloat64, value)
		_node.RewardAmount = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(rechargelotterydraw.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = &value
	}
	if value, ok := _c.mutation.ClaimedAt(); ok {
		_spec.SetField(rechargelotterydraw.FieldClaimedAt, field.TypeTime, value)
		_node.ClaimedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rechargelotterydraw.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargelotterydraw.UserTable,
			Columns: []string{rechargelotterydraw.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   rechargelotterydraw.OrderTable,
			Columns: []string{rechargelotterydraw.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeLotteryDraw.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeLotteryDrawUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeLotteryDrawCreate) OnConflict(opts ...sql.ConflictOption) *RechargeLotteryDrawUpsertOne {
	_c.conflict = opts
	return &RechargeLotteryDrawUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeLotteryDraw.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeLotteryDrawCreate) OnConflictColumns(columns ...string) *RechargeLotteryDrawUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeLotteryDrawUpsertOne{
		create: _c,
	}
}

type (
	// RechargeLotteryDrawUpsertOne is the builder for "upsert"-ing
	//  one RechargeLotteryDraw node.
	RechargeLotteryDrawUpsertOne struct {
		create *RechargeLotteryDrawCreate
	}

	// RechargeLotteryDrawUpsert is the "OnConflict" setter.
	RechargeLotteryDrawUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *RechargeLotteryDrawUpsert) SetUserID(v int64) *RechargeLotteryDrawUpsert {
	u.Set(rechargelotterydraw.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsert) UpdateUserID() *RechargeLotteryDrawUpsert {
	u.SetExcluded(rechargelotterydraw.FieldUserID)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *RechargeLotteryDrawUpsert) SetOrderID(v int64) *RechargeLotteryDrawUpsert {
	u.Set(rechargelotterydraw.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsert) UpdateOrderID() *RechargeLotteryDrawUpsert {
	u.SetExcluded(rechargelotterydraw.FieldOrderID)
	return u
}

// SetRechargeAmount sets the "recharge_amount" field.
func (u *RechargeLotteryDrawUpsert) SetRechargeAmount(v float64) *RechargeLotteryDrawUpsert {
	u.Set(rechargelotterydraw.FieldRechargeAmount, v)
	return u
}

// UpdateRechargeAmount sets the "recharge_amount" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsert) UpdateRechargeAmount() *RechargeLotteryDrawUpsert {
	u.SetExcluded(rechargelotterydraw.FieldRechargeAmount)
	return u
}

// AddRechargeAmount adds v to the "recharge_amount" field.
func (u *RechargeLotteryDrawUpsert) AddRechargeAmount(v float64) *RechargeLotteryDrawUpsert {
	u.Add(rechargelotterydraw.FieldRechargeAmount, v)
	return u
}

// SetMaxRarity sets the "max_rarity" field.
func (u *RechargeLotteryDrawUpsert) SetMaxRarity(v string) *RechargeLotteryDrawUpsert {
	u.Set(rechargelotterydraw.FieldMaxRarity, v)
	return u
}

// UpdateMaxRarity sets the "max_rarity" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsert) UpdateMaxRarity() *RechargeLotteryDrawUpsert {
	u.SetExcluded(rechargelotterydraw.FieldMaxRarity)
	return u
}

// SetRarity sets the "rarity" field.
func (u *RechargeLotteryDrawUpsert) SetRarity(v string) *RechargeLotteryDrawUpsert {
	u.Set(rechargelotterydraw.FieldRarity, v)
	return u
}

// UpdateRarity sets the "rarity" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsert) UpdateRarity() *RechargeLotteryDrawUpsert {
	u.SetExcluded(rechargelotterydraw.FieldRarity)
	return u
}

// SetRewardAmount sets the "reward_amount" field.
func (u *RechargeLotteryDrawUpsert) SetRewardAmount(v float64) *RechargeLotteryDrawUpsert {
	u.Set(rechargelotterydraw.FieldRewardAmount, v)
	return u
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsert) UpdateRewardAmount() *RechargeLotteryDrawUpsert {
	u.SetExcluded(rechargelotterydraw.FieldRewardAmount)
	return u
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *RechargeLotteryDrawUpsert) AddRewardAmount(v float64) *RechargeLotteryDrawUpsert {
	u.Add(rechargelotterydraw.FieldRewardAmount, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *RechargeLotteryDrawUpsert) SetBalanceAfter(v float64) *RechargeLotteryDrawUpsert {
	u.Set(rechargelotterydraw.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsert) UpdateBalanceAfter() *RechargeLotteryDrawUpsert {
	u.SetExcluded(rechargelotterydraw.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *RechargeLotteryDrawUpsert) AddBalanceAfter(v float64) *RechargeLotteryDrawUpsert {
	u.Add(rechargelotterydraw.FieldBalanceAfter, v)
	return u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *RechargeLotteryDrawUpsert) ClearBalanceAfter() *RechargeLotteryDrawUpsert {
	u.SetNull(rechargelotterydraw.FieldBalanceAfter)
	return u
}

// SetClaimedAt sets the "claimed_at" field.
func (u *RechargeLotteryDrawUpsert) SetClaimedAt(v time.Time) *RechargeLotteryDrawUpsert {
	u.Set(rechargelotterydraw.FieldClaimedAt, v)
	return u
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsert) UpdateClaimedAt() *RechargeLotteryDrawUpsert {
	u.SetExcluded(rechargelotterydraw.FieldClaimedAt)
	return u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *RechargeLotteryDrawUpsert) ClearClaimedAt() *RechargeLotteryDrawUpsert {
	u.SetNull(rechargelotterydraw.FieldClaimedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RechargeLotteryDraw.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeLotteryDrawUpsertOne) UpdateNewValues() *RechargeLotteryDrawUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(rechargelotterydraw.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeLotteryDraw.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RechargeLotteryDrawUpsertOne) Ignore() *RechargeLotteryDrawUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeLotteryDrawUpsertOne) DoNothing() *RechargeLotteryDrawUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeLotteryDrawCreate.OnConflict
// documentation for more info.
func (u *RechargeLotteryDrawUpsertOne) Update(set func(*RechargeLotteryDrawUpsert)) *RechargeLotteryDrawUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeLotteryDrawUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *RechargeLotteryDrawUpsertOne) SetUserID(v int64) *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertOne) UpdateUserID() *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateUserID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *RechargeLotteryDrawUpsertOne) SetOrderID(v int64) *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertOne) UpdateOrderID() *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateOrderID()
	})
}

// SetRechargeAmount sets the "recharge_amount" field.
func (u *RechargeLotteryDrawUpsertOne) SetRechargeAmount(v float64) *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetRechargeAmount(v)
	})
}

// AddRechargeAmount adds v to the "recharge_amount" field.
func (u *RechargeLotteryDrawUpsertOne) AddRechargeAmount(v float64) *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.AddRechargeAmount(v)
	})
}

// UpdateRechargeAmount sets the "recharge_amount" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertOne) UpdateRechargeAmount() *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateRechargeAmount()
	})
}

// SetMaxRarity sets the "max_rarity" field.
func (u *RechargeLotteryDrawUpsertOne) SetMaxRarity(v string) *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetMaxRarity(v)
	})
}

// UpdateMaxRarity sets the "max_rarity" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertOne) UpdateMaxRarity() *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateMaxRarity()
	})
}

// SetRarity sets the "rarity" field.
func (u *RechargeLotteryDrawUpsertOne) SetRarity(v string) *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetRarity(v)
	})
}

// UpdateRarity sets the "rarity" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertOne) UpdateRarity() *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateRarity()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *RechargeLotteryDrawUpsertOne) SetRewardAmount(v float64) *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *RechargeLotteryDrawUpsertOne) AddRewardAmount(v float64) *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertOne) UpdateRewardAmount() *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *RechargeLotteryDrawUpsertOne) SetBalanceAfter(v float64) *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *RechargeLotteryDrawUpsertOne) AddBalanceAfter(v float64) *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertOne) UpdateBalanceAfter() *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateBalanceAfter()
	})
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *RechargeLotteryDrawUpsertOne) ClearBalanceAfter() *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.ClearBalanceAfter()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *RechargeLotteryDrawUpsertOne) SetClaimedAt(v time.Time) *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertOne) UpdateClaimedAt() *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateClaimedAt()
	})
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *RechargeLotteryDrawUpsertOne) ClearClaimedAt() *RechargeLotteryDrawUpsertOne {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.ClearClaimedAt()
	})
}

// Exec executes the query.
func (u *RechargeLotteryDrawUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeLotteryDrawCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeLotteryDrawUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RechargeLotteryDrawUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RechargeLotteryDrawUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RechargeLotteryDrawCreateBulk is the builder for creating many RechargeLotteryDraw entities in bulk.
type RechargeLotteryDrawCreateBulk struct {
	config
	err      error
	builders []*RechargeLotteryDrawCreate
	conflict []sql.ConflictOption
}

// Save creates the RechargeLotteryDraw entities in the database.
func (_c *RechargeLotteryDrawCreateBulk) Save(ctx context.Context) ([]*RechargeLotteryDraw, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RechargeLotteryDraw, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RechargeLotteryDrawMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RechargeLotteryDrawCreateBulk) SaveX(ctx context.Context) []*RechargeLotteryDraw {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeLotteryDrawCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeLotteryDrawCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeLotteryDraw.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeLotteryDrawUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeLotteryDrawCreateBulk) OnConflict(opts ...sql.ConflictOption) *RechargeLotteryDrawUpsertBulk {
	_c.conflict = opts
	return &RechargeLotteryDrawUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeLotteryDraw.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeLotteryDrawCreateBulk) OnConflictColumns(columns ...string) *RechargeLotteryDrawUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeLotteryDrawUpsertBulk{
		create: _c,
	}
}

// RechargeLotteryDrawUpsertBulk is the builder for "upsert"-ing
// a bulk of RechargeLotteryDraw nodes.
type RechargeLotteryDrawUpsertBulk struct {
	create *RechargeLotteryDrawCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RechargeLotteryDraw.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeLotteryDrawUpsertBulk) UpdateNewValues() *RechargeLotteryDrawUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(rechargelotterydraw.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeLotteryDraw.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RechargeLotteryDrawUpsertBulk) Ignore() *RechargeLotteryDrawUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeLotteryDrawUpsertBulk) DoNothing() *RechargeLotteryDrawUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeLotteryDrawCreateBulk.OnConflict
// documentation for more info.
func (u *RechargeLotteryDrawUpsertBulk) Update(set func(*RechargeLotteryDrawUpsert)) *RechargeLotteryDrawUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeLotteryDrawUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *RechargeLotteryDrawUpsertBulk) SetUserID(v int64) *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertBulk) UpdateUserID() *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateUserID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *RechargeLotteryDrawUpsertBulk) SetOrderID(v int64) *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertBulk) UpdateOrderID() *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateOrderID()
	})
}

// SetRechargeAmount sets the "recharge_amount" field.
func (u *RechargeLotteryDrawUpsertBulk) SetRechargeAmount(v float64) *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetRechargeAmount(v)
	})
}

// AddRechargeAmount adds v to the "recharge_amount" field.
func (u *RechargeLotteryDrawUpsertBulk) AddRechargeAmount(v float64) *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.AddRechargeAmount(v)
	})
}

// UpdateRechargeAmount sets the "recharge_amount" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertBulk) UpdateRechargeAmount() *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateRechargeAmount()
	})
}

// SetMaxRarity sets the "max_rarity" field.
func (u *RechargeLotteryDrawUpsertBulk) SetMaxRarity(v string) *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetMaxRarity(v)
	})
}

// UpdateMaxRarity sets the "max_rarity" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertBulk) UpdateMaxRarity() *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateMaxRarity()
	})
}

// SetRarity sets the "rarity" field.
func (u *RechargeLotteryDrawUpsertBulk) SetRarity(v string) *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetRarity(v)
	})
}

// UpdateRarity sets the "rarity" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertBulk) UpdateRarity() *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateRarity()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *RechargeLotteryDrawUpsertBulk) SetRewardAmount(v float64) *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *RechargeLotteryDrawUpsertBulk) AddRewardAmount(v float64) *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertBulk) UpdateRewardAmount() *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *RechargeLotteryDrawUpsertBulk) SetBalanceAfter(v float64) *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *RechargeLotteryDrawUpsertBulk) AddBalanceAfter(v float64) *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertBulk) UpdateBalanceAfter() *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateBalanceAfter()
	})
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *RechargeLotteryDrawUpsertBulk) ClearBalanceAfter() *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.ClearBalanceAfter()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *RechargeLotteryDrawUpsertBulk) SetClaimedAt(v time.Time) *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *RechargeLotteryDrawUpsertBulk) UpdateClaimedAt() *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.UpdateClaimedAt()
	})
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *RechargeLotteryDrawUpsertBulk) ClearClaimedAt() *RechargeLotteryDrawUpsertBulk {
	return u.Update(func(s *RechargeLotteryDrawUpsert) {
		s.ClearClaimedAt()
	})
}

// Exec executes the query.
func (u *RechargeLotteryDrawUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RechargeLotteryDrawCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeLotteryDrawCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeLotteryDrawUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
