// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargelotterydraw"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RechargeLotteryDrawUpdate is the builder for updating RechargeLotteryDraw entities.
type RechargeLotteryDrawUpdate struct {
	config
	hooks    []Hook
	mutation *RechargeLotteryDrawMutation
}

// Where appends a list predicates to the RechargeLotteryDrawUpdate builder.
func (_u *RechargeLotteryDrawUpdate) Where(ps ...predicate.RechargeLotteryDraw) *RechargeLotteryDrawUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RechargeLotteryDrawUpdate) SetUserID(v int64) *RechargeLotteryDrawUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdate) SetNillableUserID(v *int64) *RechargeLotteryDrawUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *RechargeLotteryDrawUpdate) SetOrderID(v int64) *RechargeLotteryDrawUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdate) SetNillableOrderID(v *int64) *RechargeLotteryDrawUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetRechargeAmount sets the "recharge_amount" field.
func (_u *RechargeLotteryDrawUpdate) SetRechargeAmount(v float64) *RechargeLotteryDrawUpdate {
	_u.mutation.ResetRechargeAmount()
	_u.mutation.SetRechargeAmount(v)
	return _u
}

// SetNillableRechargeAmount sets the "recharge_amount" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdate) SetNillableRechargeAmount(v *float64) *RechargeLotteryDrawUpdate {
	if v != nil {
		_u.SetRechargeAmount(*v)
	}
	return _u
}

// AddRechargeAmount adds value to the "recharge_amount" field.
func (_u *RechargeLotteryDrawUpdate) AddRechargeAmount(v float64) *RechargeLotteryDrawUpdate {
	_u.mutation.AddRechargeAmount(v)
	return _u
}

// SetMaxRarity sets the "max_rarity" field.
func (_u *RechargeLotteryDrawUpdate) SetMaxRarity(v string) *RechargeLotteryDrawUpdate {
	_u.mutation.SetMaxRarity(v)
	return _u
}

// SetNillableMaxRarity sets the "max_rarity" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdate) SetNillableMaxRarity(v *string) *RechargeLotteryDrawUpdate {
	if v != nil {
		_u.SetMaxRarity(*v)
	}
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *RechargeLotteryDrawUpdate) SetRarity(v string) *RechargeLotteryDrawUpdate {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdate) SetNillableRarity(v *string) *RechargeLotteryDrawUpdate {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *RechargeLotteryDrawUpdate) SetRewardAmount(v float64) *RechargeLotteryDrawUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdate) SetNillableRewardAmount(v *float64) *RechargeLotteryDrawUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *RechargeLotteryDrawUpdate) AddRewardAmount(v float64) *RechargeLotteryDrawUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *RechargeLotteryDrawUpdate) SetBalanceAfter(v float64) *RechargeLotteryDrawUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdate) SetNillableBalanceAfter(v *float64) *RechargeLotteryDrawUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *RechargeLotteryDrawUpdate) AddBalanceAfter(v float64) *RechargeLotteryDrawUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *RechargeLotteryDrawUpdate) ClearBalanceAfter() *RechargeLotteryDrawUpdate {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *RechargeLotteryDrawUpdate) SetClaimedAt(v time.Time) *RechargeLotteryDrawUpdate {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdate) SetNillableClaimedAt(v *time.Time) *RechargeLotteryDrawUpdate {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *RechargeLotteryDrawUpdate) ClearClaimedAt() *RechargeLotteryDrawUpdate {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RechargeLotteryDrawUpdate) SetUser(v *User) *RechargeLotteryDrawUpdate {
	return _u.SetUserID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_u *RechargeLotteryDrawUpdate) SetOrder(v *PaymentOrder) *RechargeLotteryDrawUpdate {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the RechargeLotteryDrawMutation object of the builder.
func (_u *RechargeLotteryDrawUpdate) Mutation() *RechargeLotteryDrawMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RechargeLotteryDrawUpdate) ClearUser() *RechargeLotteryDrawUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrder clears the "order" edge to the PaymentOrder entity.
func (_u *RechargeLotteryDrawUpdate) ClearOrder() *RechargeLotteryDrawUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RechargeLotteryDrawUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeLotteryDrawUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RechargeLotteryDrawUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeLotteryDrawUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeLotteryDrawUpdate) check() error {
	if v, ok := _u.mutation.MaxRarity(); ok {
		if err := rechargelotterydraw.MaxRarityValidator(v); err != nil {
			return &ValidationError{Name: "max_rarity", err: fmt.Errorf(`ent: validator failed for field "RechargeLotteryDraw.max_rarity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rarity(); ok {
		if err := rechargelotterydraw.RarityValidator(v); err != nil {
			return &ValidationError{Name: "rarity", err: fmt.Errorf(`ent: validator failed for field "RechargeLotteryDraw.rarity": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RechargeLotteryDraw.user"`)
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RechargeLotteryDraw.order"`)
	}
	return nil
}

func (_u *RechargeLotteryDrawUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargelotterydraw.Table, rechargelotterydraw.Columns, sqlgraph.NewFieldSpec(rechargelotterydraw.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RechargeAmount(); ok {
		_spec.SetField(rechargelotterydraw.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRechargeAmount(); ok {
		_spec.AddField(rechargelotterydraw.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxRarity(); ok {
		_spec.SetField(rechargelotterydraw.FieldMaxRarity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(rechargelotterydraw.FieldRarity, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(rechargelotterydraw.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(rechargelotterydraw.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(rechargelotterydraw.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(rechargelotterydraw.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(rechargelotterydraw.FieldBalanceAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(rechargelotterydraw.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(rechargelotterydraw.FieldClaimedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargelotterydraw.UserTable,
			Columns: []string{rechargelotterydraw.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargelotterydraw.UserTable,
			Columns: []string{rechargelotterydraw.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   rechargelotterydraw.OrderTable,
			Columns: []string{rechargelotterydraw.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   rechargelotterydraw.OrderTable,
			Columns: []string{rechargelotterydraw.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargelotterydraw.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RechargeLotteryDrawUpdateOne is the builder for updating a single RechargeLotteryDraw entity.
type RechargeLotteryDrawUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RechargeLotteryDrawMutation
}

// SetUserID sets the "user_id" field.
func (_u *RechargeLotteryDrawUpdateOne) SetUserID(v int64) *RechargeLotteryDrawUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdateOne) SetNillableUserID(v *int64) *RechargeLotteryDrawUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *RechargeLotteryDrawUpdateOne) SetOrderID(v int64) *RechargeLotteryDrawUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdateOne) SetNillableOrderID(v *int64) *RechargeLotteryDrawUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetRechargeAmount sets the "recharge_amount" field.
func (_u *RechargeLotteryDrawUpdateOne) SetRechargeAmount(v float64) *RechargeLotteryDrawUpdateOne {
	_u.mutation.ResetRechargeAmount()
	_u.mutation.SetRechargeAmount(v)
	return _u
}

// SetNillableRechargeAmount sets the "recharge_amount" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdateOne) SetNillableRechargeAmount(v *float64) *RechargeLotteryDrawUpdateOne {
	if v != nil {
		_u.SetRechargeAmount(*v)
	}
	return _u
}

// AddRechargeAmount adds value to the "recharge_amount" field.
func (_u *RechargeLotteryDrawUpdateOne) AddRechargeAmount(v float64) *RechargeLotteryDrawUpdateOne {
	_u.mutation.AddRechargeAmount(v)
	return _u
}

// SetMaxRarity sets the "max_rarity" field.
func (_u *RechargeLotteryDrawUpdateOne) SetMaxRarity(v string) *RechargeLotteryDrawUpdateOne {
	_u.mutation.SetMaxRarity(v)
	return _u
}

// SetNillableMaxRarity sets the "max_rarity" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdateOne) SetNillableMaxRarity(v *string) *RechargeLotteryDrawUpdateOne {
	if v != nil {
		_u.SetMaxRarity(*v)
	}
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *RechargeLotteryDrawUpdateOne) SetRarity(v string) *RechargeLotteryDrawUpdateOne {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdateOne) SetNillableRarity(v *string) *RechargeLotteryDrawUpdateOne {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *RechargeLotteryDrawUpdateOne) SetRewardAmount(v float64) *RechargeLotteryDrawUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdateOne) SetNillableRewardAmount(v *float64) *RechargeLotteryDrawUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *RechargeLotteryDrawUpdateOne) AddRewardAmount(v float64) *RechargeLotteryDrawUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *RechargeLotteryDrawUpdateOne) SetBalanceAfter(v float64) *RechargeLotteryDrawUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdateOne) SetNillableBalanceAfter(v *float64) *RechargeLotteryDrawUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *RechargeLotteryDrawUpdateOne) AddBalanceAfter(v float64) *RechargeLotteryDrawUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *RechargeLotteryDrawUpdateOne) ClearBalanceAfter() *RechargeLotteryDrawUpdateOne {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *RechargeLotteryDrawUpdateOne) SetClaimedAt(v time.Time) *RechargeLotteryDrawUpdateOne {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *RechargeLotteryDrawUpdateOne) SetNillableClaimedAt(v *time.Time) *RechargeLotteryDrawUpdateOne {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *RechargeLotteryDrawUpdateOne) ClearClaimedAt() *RechargeLotteryDrawUpdateOne {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RechargeLotteryDrawUpdateOne) SetUser(v *User) *RechargeLotteryDrawUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_u *RechargeLotteryDrawUpdateOne) SetOrder(v *PaymentOrder) *RechargeLotteryDrawUpdateOne {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the RechargeLotteryDrawMutation object of the builder.
func (_u *RechargeLotteryDrawUpdateOne) Mutation() *RechargeLotteryDrawMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RechargeLotteryDrawUpdateOne) ClearUser() *RechargeLotteryDrawUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrder clears the "order" edge to the PaymentOrder entity.
func (_u *RechargeLotteryDrawUpdateOne) ClearOrder() *RechargeLotteryDrawUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// Where appends a list predicates to the RechargeLotteryDrawUpdate builder.
func (_u *RechargeLotteryDrawUpdateOne) Where(ps ...predicate.RechargeLotteryDraw) *RechargeLotteryDrawUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RechargeLotteryDrawUpdateOne) Select(field string, fields ...string) *RechargeLotteryDrawUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RechargeLotteryDraw entity.
func (_u *RechargeLotteryDrawUpdateOne) Save(ctx context.Context) (*RechargeLotteryDraw, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeLotteryDrawUpdateOne) SaveX(ctx context.Context) *RechargeLotteryDraw {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RechargeLotteryDrawUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeLotteryDrawUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeLotteryDrawUpdateOne) check() error {
	if v, ok := _u.mutation.MaxRarity(); ok {
		if err := rechargelotterydraw.MaxRarityValidator(v); err != nil {
			return &ValidationError{Name: "max_rarity", err: fmt.Errorf(`ent: validator failed for field "RechargeLotteryDraw.max_rarity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rarity(); ok {
		if err := rechargelotterydraw.RarityValidator(v); err != nil {
			return &ValidationError{Name: "rarity", err: fmt.Errorf(`ent: validator failed for field "RechargeLotteryDraw.rarity": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RechargeLotteryDraw.user"`)
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RechargeLotteryDraw.order"`)
	}
	return nil
}

func (_u *RechargeLotteryDrawUpdateOne) sqlSave(ctx context.Context) (_node *RechargeLotteryDraw, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargelotterydraw.Table, rechargelotterydraw.Columns, sqlgraph.NewFieldSpec(rechargelotterydraw.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RechargeLotteryDraw.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rechargelotterydraw.FieldID)
		for _, f := range fields {
			if !rechargelotterydraw.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rechargelotterydraw.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RechargeAmount(); ok {
		_spec.SetField(rechargelotterydraw.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRechargeAmount(); ok {
		_spec.AddField(rechargelotterydraw.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxRarity(); ok {
		_spec.SetField(rechargelotterydraw.FieldMaxRarity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(rechargelotterydraw.FieldRarity, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(rechargelotterydraw.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(rechargelotterydraw.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(rechargelotterydraw.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(rechargelotterydraw.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(rechargelotterydraw.FieldBalanceAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(rechargelotterydraw.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(rechargelotterydraw.FieldClaimedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargelotterydraw.UserTable,
			Columns: []string{rechargelotterydraw.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargelotterydraw.UserTable,
			Columns: []string{rechargelotterydraw.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   rechargelotterydraw.OrderTable,
			Columns: []string{rechargelotterydraw.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   rechargelotterydraw.OrderTable,
			Columns: []string{rechargelotterydraw.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RechargeLotteryDraw{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargelotterydraw.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
