// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargelotterydraw"
)

// RechargeLotteryDrawDelete is the builder for deleting a RechargeLotteryDraw entity.
type RechargeLotteryDrawDelete struct {
	config
	hooks    []Hook
	mutation *RechargeLotteryDrawMutation
}

// Where appends a list predicates to the RechargeLotteryDrawDelete builder.
func (_d *RechargeLotteryDrawDelete) Where(ps ...predicate.RechargeLotteryDraw) *RechargeLotteryDrawDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RechargeLotteryDrawDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RechargeLotteryDrawDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RechargeLotteryDrawDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rechargelotterydraw.Table, sqlgraph.NewFieldSpec(rechargelotterydraw.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RechargeLotteryDrawDeleteOne is the builder for deleting a single RechargeLotteryDraw entity.
type RechargeLotteryDrawDeleteOne struct {
	_d *RechargeLotteryDrawDelete
}

// Where appends a list predicates to the RechargeLotteryDrawDelete builder.
func (_d *RechargeLotteryDrawDeleteOne) Where(ps ...predicate.RechargeLotteryDraw) *RechargeLotteryDrawDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RechargeLotteryDrawDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rechargelotterydraw.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RechargeLotteryDrawDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
