// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/rechargelotterydraw"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RechargeLotteryDraw is the model entity for the RechargeLotteryDraw schema.
type RechargeLotteryDraw struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int64 `json:"order_id,omitempty"`
	// RechargeAmount holds the value of the "recharge_amount" field.
	RechargeAmount float64 `json:"recharge_amount,omitempty"`
	// MaxRarity holds the value of the "max_rarity" field.
	MaxRarity string `json:"max_rarity,omitempty"`
	// Rarity holds the value of the "rarity" field.
	Rarity string `json:"rarity,omitempty"`
	// RewardAmount holds the value of the "reward_amount" field.
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter *float64 `json:"balance_after,omitempty"`
	// ClaimedAt holds the value of the "claimed_at" field.
	ClaimedAt *time.Time `json:"claimed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RechargeLotteryDrawQuery when eager-loading is set.
	Edges        RechargeLotteryDrawEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RechargeLotteryDrawEdges holds the relations/edges for other nodes in the graph.
type RechargeLotteryDrawEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Order holds the value of the order edge.
	Order *PaymentOrder `json:"order,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeLotteryDrawEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeLotteryDrawEdges) OrderOrErr() (*PaymentOrder, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RechargeLotteryDraw) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rechargelotterydraw.FieldRechargeAmount, rechargelotterydraw.FieldRewardAmount, rechargelotterydraw.FieldBalanceAfter:
			values[i] = new(sql.NullFloat64)
		case rechargelotterydraw.FieldID, rechargelotterydraw.FieldUserID, rechargelotterydraw.FieldOrderID:
			values[i] = new(sql.NullInt64)
		case rechargelotterydraw.FieldMaxRarity, rechargelotterydraw.FieldRarity:
			values[i] = new(sql.NullString)
		case rechargelotterydraw.FieldClaimedAt, rechargelotterydraw.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RechargeLotteryDraw fields.
func (_m *RechargeLotteryDraw) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rechargelotterydraw.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case rechargelotterydraw.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case rechargelotterydraw.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case rechargelotterydraw.FieldRechargeAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field recharge_amount", values[i])
			} else if value.Valid {
				_m.RechargeAmount = value.Float64
			}
		case rechargelotterydraw.FieldMaxRarity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field max_rarity", values[i])
			} else if value.Valid {
				_m.MaxRarity = value.String
			}
		case rechargelotterydraw.FieldRarity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rarity", values[i])
			} else if value.Valid {
				_m.Rarity = value.String
			}
		case rechargelotterydraw.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		case rechargelotterydraw.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = new(float64)
				*_m.BalanceAfter = value.Float64
			}
		case rechargelotterydraw.FieldClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_at", values[i])
			} else if value.Valid {
				_m.ClaimedAt = new(time.Time)
				*_m.ClaimedAt = value.Time
			}
		case rechargelotterydraw.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RechargeLotteryDraw.
// This includes values selected through modifiers, order, etc.
func (_m *RechargeLotteryDraw) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the RechargeLotteryDraw entity.
func (_m *RechargeLotteryDraw) QueryUser() *UserQuery {
	return NewRechargeLotteryDrawClient(_m.config).QueryUser(_m)
}

// QueryOrder queries the "order" edge of the RechargeLotteryDraw entity.
func (_m *RechargeLotteryDraw) QueryOrder() *PaymentOrderQuery {
	return NewRechargeLotteryDrawClient(_m.config).QueryOrder(_m)
}

// Update returns a builder for updating this RechargeLotteryDraw.
// Note that you need to call RechargeLotteryDraw.Unwrap() before calling this method if this RechargeLotteryDraw
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RechargeLotteryDraw) Update() *RechargeLotteryDrawUpdateOne {
	return NewRechargeLotteryDrawClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RechargeLotteryDraw entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RechargeLotteryDraw) Unwrap() *RechargeLotteryDraw {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RechargeLotteryDraw is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RechargeLotteryDraw) String() string {
	var builder strings.Builder
	builder.WriteString("RechargeLotteryDraw(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("recharge_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RechargeAmount))
	builder.WriteString(", ")
	builder.WriteString("max_rarity=")
	builder.WriteString(_m.MaxRarity)
	builder.WriteString(", ")
	builder.WriteString("rarity=")
	builder.WriteString(_m.Rarity)
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteString(", ")
	if v := _m.BalanceAfter; v != nil {
		builder.WriteString("balance_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ClaimedAt; v != nil {
		builder.WriteString("claimed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RechargeLotteryDraws is a parsable slice of RechargeLotteryDraw.
type RechargeLotteryDraws []*RechargeLotteryDraw
