// Code generated by ent, DO NOT EDIT.

package rechargelotterydraw

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the rechargelotterydraw type in the database.
	Label = "recharge_lottery_draw"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldRechargeAmount holds the string denoting the recharge_amount field in the database.
	FieldRechargeAmount = "recharge_amount"
	// FieldMaxRarity holds the string denoting the max_rarity field in the database.
	FieldMaxRarity = "max_rarity"
	// FieldRarity holds the string denoting the rarity field in the database.
	FieldRarity = "rarity"
	// FieldRewardAmount holds the string denoting the reward_amount field in the database.
	FieldRewardAmount = "reward_amount"
	// FieldBalanceAfter holds the string denoting the balance_after field in the database.
	FieldBalanceAfter = "balance_after"
	// FieldClaimedAt holds the string denoting the claimed_at field in the database.
	FieldClaimedAt = "claimed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeOrder holds the string denoting the order edge name in mutations.
	EdgeOrder = "order"
	// Table holds the table name of the rechargelotterydraw in the database.
	Table = "recharge_lottery_draws"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "recharge_lottery_draws"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// OrderTable is the table that holds the order relation/edge.
	OrderTable = "recharge_lottery_draws"
	// OrderInverseTable is the table name for the PaymentOrder entity.
	// It exists in this package in order to avoid circular dependency with the "paymentorder" package.
	OrderInverseTable = "payment_orders"
	// OrderColumn is the table column denoting the order relation/edge.
	OrderColumn = "order_id"
)

// Columns holds all SQL columns for rechargelotterydraw fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldOrderID,
	FieldRechargeAmount,
	FieldMaxRarity,
	FieldRarity,
	FieldRewardAmount,
	FieldBalanceAfter,
	FieldClaimedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// MaxRarityValidator is a validator for the "max_rarity" field. It is called by the builders before save.
	MaxRarityValidator func(string) error
	// DefaultRarity holds the default value on creation for the "rarity" field.
	DefaultRarity string
	// RarityValidator is a validator for the "rarity" field. It is called by the builders before save.
	RarityValidator func(string) error
	// DefaultRewardAmount holds the default value on creation for the "reward_amount" field.
	DefaultRewardAmount float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the RechargeLotteryDraw queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByRechargeAmount orders the results by the recharge_amount field.
func ByRechargeAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeAmount, opts...).ToFunc()
}

// ByMaxRarity orders the results by the max_rarity field.
func ByMaxRarity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxRarity, opts...).ToFunc()
}

// ByRarity orders the results by the rarity field.
func ByRarity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRarity, opts...).ToFunc()
}

// ByRewardAmount orders the results by the reward_amount field.
func ByRewardAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardAmount, opts...).ToFunc()
}

// ByBalanceAfter orders the results by the balance_after field.
func ByBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfter, opts...).ToFunc()
}

// ByClaimedAt orders the results by the claimed_at field.
func ByClaimedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrderField orders the results by order field.
func ByOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OrderTable, OrderColumn),
	)
}
