// Code generated by ent, DO NOT EDIT.

package rechargelotterydraw

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldUserID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldOrderID, v))
}

// RechargeAmount applies equality check predicate on the "recharge_amount" field. It's identical to RechargeAmountEQ.
func RechargeAmount(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldRechargeAmount, v))
}

// MaxRarity applies equality check predicate on the "max_rarity" field. It's identical to MaxRarityEQ.
func MaxRarity(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldMaxRarity, v))
}

// Rarity applies equality check predicate on the "rarity" field. It's identical to RarityEQ.
func Rarity(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldRarity, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldRewardAmount, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldBalanceAfter, v))
}

// ClaimedAt applies equality check predicate on the "claimed_at" field. It's identical to ClaimedAtEQ.
func ClaimedAt(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldClaimedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotIn(FieldUserID, vs...))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotIn(FieldOrderID, vs...))
}

// RechargeAmountEQ applies the EQ predicate on the "recharge_amount" field.
func RechargeAmountEQ(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldRechargeAmount, v))
}

// RechargeAmountNEQ applies the NEQ predicate on the "recharge_amount" field.
func RechargeAmountNEQ(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNEQ(FieldRechargeAmount, v))
}

// RechargeAmountIn applies the In predicate on the "recharge_amount" field.
func RechargeAmountIn(vs ...float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIn(FieldRechargeAmount, vs...))
}

// RechargeAmountNotIn applies the NotIn predicate on the "recharge_amount" field.
func RechargeAmountNotIn(vs ...float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotIn(FieldRechargeAmount, vs...))
}

// RechargeAmountGT applies the GT predicate on the "recharge_amount" field.
func RechargeAmountGT(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGT(FieldRechargeAmount, v))
}

// RechargeAmountGTE applies the GTE predicate on the "recharge_amount" field.
func RechargeAmountGTE(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGTE(FieldRechargeAmount, v))
}

// RechargeAmountLT applies the LT predicate on the "recharge_amount" field.
func RechargeAmountLT(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLT(FieldRechargeAmount, v))
}

// RechargeAmountLTE applies the LTE predicate on the "recharge_amount" field.
func RechargeAmountLTE(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLTE(FieldRechargeAmount, v))
}

// MaxRarityEQ applies the EQ predicate on the "max_rarity" field.
func MaxRarityEQ(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldMaxRarity, v))
}

// MaxRarityNEQ applies the NEQ predicate on the "max_rarity" field.
func MaxRarityNEQ(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNEQ(FieldMaxRarity, v))
}

// MaxRarityIn applies the In predicate on the "max_rarity" field.
func MaxRarityIn(vs ...string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIn(FieldMaxRarity, vs...))
}

// MaxRarityNotIn applies the NotIn predicate on the "max_rarity" field.
func MaxRarityNotIn(vs ...string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotIn(FieldMaxRarity, vs...))
}

// MaxRarityGT applies the GT predicate on the "max_rarity" field.
func MaxRarityGT(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGT(FieldMaxRarity, v))
}

// MaxRarityGTE applies the GTE predicate on the "max_rarity" field.
func MaxRarityGTE(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGTE(FieldMaxRarity, v))
}

// MaxRarityLT applies the LT predicate on the "max_rarity" field.
func MaxRarityLT(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLT(FieldMaxRarity, v))
}

// MaxRarityLTE applies the LTE predicate on the "max_rarity" field.
func MaxRarityLTE(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLTE(FieldMaxRarity, v))
}

// MaxRarityContains applies the Contains predicate on the "max_rarity" field.
func MaxRarityContains(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldContains(FieldMaxRarity, v))
}

// MaxRarityHasPrefix applies the HasPrefix predicate on the "max_rarity" field.
func MaxRarityHasPrefix(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldHasPrefix(FieldMaxRarity, v))
}

// MaxRarityHasSuffix applies the HasSuffix predicate on the "max_rarity" field.
func MaxRarityHasSuffix(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldHasSuffix(FieldMaxRarity, v))
}

// MaxRarityEqualFold applies the EqualFold predicate on the "max_rarity" field.
func MaxRarityEqualFold(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEqualFold(FieldMaxRarity, v))
}

// MaxRarityContainsFold applies the ContainsFold predicate on the "max_rarity" field.
func MaxRarityContainsFold(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldContainsFold(FieldMaxRarity, v))
}

// RarityEQ applies the EQ predicate on the "rarity" field.
func RarityEQ(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldRarity, v))
}

// RarityNEQ applies the NEQ predicate on the "rarity" field.
func RarityNEQ(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNEQ(FieldRarity, v))
}

// RarityIn applies the In predicate on the "rarity" field.
func RarityIn(vs ...string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIn(FieldRarity, vs...))
}

// RarityNotIn applies the NotIn predicate on the "rarity" field.
func RarityNotIn(vs ...string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotIn(FieldRarity, vs...))
}

// RarityGT applies the GT predicate on the "rarity" field.
func RarityGT(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGT(FieldRarity, v))
}

// RarityGTE applies the GTE predicate on the "rarity" field.
func RarityGTE(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGTE(FieldRarity, v))
}

// RarityLT applies the LT predicate on the "rarity" field.
func RarityLT(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLT(FieldRarity, v))
}

// RarityLTE applies the LTE predicate on the "rarity" field.
func RarityLTE(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLTE(FieldRarity, v))
}

// RarityContains applies the Contains predicate on the "rarity" field.
func RarityContains(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldContains(FieldRarity, v))
}

// RarityHasPrefix applies the HasPrefix predicate on the "rarity" field.
func RarityHasPrefix(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldHasPrefix(FieldRarity, v))
}

// RarityHasSuffix applies the HasSuffix predicate on the "rarity" field.
func RarityHasSuffix(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldHasSuffix(FieldRarity, v))
}

// RarityEqualFold applies the EqualFold predicate on the "rarity" field.
func RarityEqualFold(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEqualFold(FieldRarity, v))
}

// RarityContainsFold applies the ContainsFold predicate on the "rarity" field.
func RarityContainsFold(v string) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldContainsFold(FieldRarity, v))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLTE(FieldRewardAmount, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v float64) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLTE(FieldBalanceAfter, v))
}

// BalanceAfterIsNil applies the IsNil predicate on the "balance_after" field.
func BalanceAfterIsNil() predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIsNull(FieldBalanceAfter))
}

// BalanceAfterNotNil applies the NotNil predicate on the "balance_after" field.
func BalanceAfterNotNil() predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotNull(FieldBalanceAfter))
}

// ClaimedAtEQ applies the EQ predicate on the "claimed_at" field.
func ClaimedAtEQ(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldClaimedAt, v))
}

// ClaimedAtNEQ applies the NEQ predicate on the "claimed_at" field.
func ClaimedAtNEQ(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNEQ(FieldClaimedAt, v))
}

// ClaimedAtIn applies the In predicate on the "claimed_at" field.
func ClaimedAtIn(vs ...time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIn(FieldClaimedAt, vs...))
}

// ClaimedAtNotIn applies the NotIn predicate on the "claimed_at" field.
func ClaimedAtNotIn(vs ...time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotIn(FieldClaimedAt, vs...))
}

// ClaimedAtGT applies the GT predicate on the "claimed_at" field.
func ClaimedAtGT(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGT(FieldClaimedAt, v))
}

// ClaimedAtGTE applies the GTE predicate on the "claimed_at" field.
func ClaimedAtGTE(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGTE(FieldClaimedAt, v))
}

// ClaimedAtLT applies the LT predicate on the "claimed_at" field.
func ClaimedAtLT(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLT(FieldClaimedAt, v))
}

// ClaimedAtLTE applies the LTE predicate on the "claimed_at" field.
func ClaimedAtLTE(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLTE(FieldClaimedAt, v))
}

// ClaimedAtIsNil applies the IsNil predicate on the "claimed_at" field.
func ClaimedAtIsNil() predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIsNull(FieldClaimedAt))
}

// ClaimedAtNotNil applies the NotNil predicate on the "claimed_at" field.
func ClaimedAtNotNil() predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotNull(FieldClaimedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.PaymentOrder) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RechargeLotteryDraw) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RechargeLotteryDraw) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RechargeLotteryDraw) predicate.RechargeLotteryDraw {
	return predicate.RechargeLotteryDraw(sql.NotPredicates(p))
}
