// Code generated by ent, DO NOT EDIT.

package carpoolgroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the carpoolgroup type in the database.
	Label = "carpool_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCarpoolPlanID holds the string denoting the carpool_plan_id field in the database.
	FieldCarpoolPlanID = "carpool_plan_id"
	// FieldCarpoolPlanRevision holds the string denoting the carpool_plan_revision field in the database.
	FieldCarpoolPlanRevision = "carpool_plan_revision"
	// FieldTargetMembers holds the string denoting the target_members field in the database.
	FieldTargetMembers = "target_members"
	// FieldTotalAmount holds the string denoting the total_amount field in the database.
	FieldTotalAmount = "total_amount"
	// FieldPricePerMember holds the string denoting the price_per_member field in the database.
	FieldPricePerMember = "price_per_member"
	// FieldPlanNote holds the string denoting the plan_note field in the database.
	FieldPlanNote = "plan_note"
	// FieldMemberCount holds the string denoting the member_count field in the database.
	FieldMemberCount = "member_count"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldOpenKey holds the string denoting the open_key field in the database.
	FieldOpenKey = "open_key"
	// FieldStatusReason holds the string denoting the status_reason field in the database.
	FieldStatusReason = "status_reason"
	// FieldDeadlineAt holds the string denoting the deadline_at field in the database.
	FieldDeadlineAt = "deadline_at"
	// FieldFormedAt holds the string denoting the formed_at field in the database.
	FieldFormedAt = "formed_at"
	// FieldOpenedAt holds the string denoting the opened_at field in the database.
	FieldOpenedAt = "opened_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOrders holds the string denoting the orders edge name in mutations.
	EdgeOrders = "orders"
	// Table holds the table name of the carpoolgroup in the database.
	Table = "carpool_groups"
	// OrdersTable is the table that holds the orders relation/edge.
	OrdersTable = "payment_orders"
	// OrdersInverseTable is the table name for the PaymentOrder entity.
	// It exists in this package in order to avoid circular dependency with the "paymentorder" package.
	OrdersInverseTable = "payment_orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "carpool_group_id"
)

// Columns holds all SQL columns for carpoolgroup fields.
var Columns = []string{
	FieldID,
	FieldCarpoolPlanID,
	FieldCarpoolPlanRevision,
	FieldTargetMembers,
	FieldTotalAmount,
	FieldPricePerMember,
	FieldPlanNote,
	FieldMemberCount,
	FieldStatus,
	FieldOpenKey,
	FieldStatusReason,
	FieldDeadlineAt,
	FieldFormedAt,
	FieldOpenedAt,
	FieldExpiresAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultMemberCount holds the default value on creation for the "member_count" field.
	DefaultMemberCount int
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// OpenKeyValidator is a validator for the "open_key" field. It is called by the builders before save.
	OpenKeyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CarpoolGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCarpoolPlanID orders the results by the carpool_plan_id field.
func ByCarpoolPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCarpoolPlanID, opts...).ToFunc()
}

// ByCarpoolPlanRevision orders the results by the carpool_plan_revision field.
func ByCarpoolPlanRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCarpoolPlanRevision, opts...).ToFunc()
}

// ByTargetMembers orders the results by the target_members field.
func ByTargetMembers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetMembers, opts...).ToFunc()
}

// ByTotalAmount orders the results by the total_amount field.
func ByTotalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAmount, opts...).ToFunc()
}

// ByPricePerMember orders the results by the price_per_member field.
func ByPricePerMember(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricePerMember, opts...).ToFunc()
}

// ByPlanNote orders the results by the plan_note field.
func ByPlanNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanNote, opts...).ToFunc()
}

// ByMemberCount orders the results by the member_count field.
func ByMemberCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberCount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByOpenKey orders the results by the open_key field.
func ByOpenKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpenKey, opts...).ToFunc()
}

// ByStatusReason orders the results by the status_reason field.
func ByStatusReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusReason, opts...).ToFunc()
}

// ByDeadlineAt orders the results by the deadline_at field.
func ByDeadlineAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeadlineAt, opts...).ToFunc()
}

// ByFormedAt orders the results by the formed_at field.
func ByFormedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFormedAt, opts...).ToFunc()
}

// ByOpenedAt orders the results by the opened_at field.
func ByOpenedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpenedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrdersCount orders the results by orders count.
func ByOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrdersStep(), opts...)
	}
}

// ByOrders orders the results by orders terms.
func ByOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
	)
}
