// Code generated by ent, DO NOT EDIT.

package carpoolgroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldID, id))
}

// CarpoolPlanID applies equality check predicate on the "carpool_plan_id" field. It's identical to CarpoolPlanIDEQ.
func CarpoolPlanID(v int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldCarpoolPlanID, v))
}

// CarpoolPlanRevision applies equality check predicate on the "carpool_plan_revision" field. It's identical to CarpoolPlanRevisionEQ.
func CarpoolPlanRevision(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldCarpoolPlanRevision, v))
}

// TargetMembers applies equality check predicate on the "target_members" field. It's identical to TargetMembersEQ.
func TargetMembers(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldTargetMembers, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldTotalAmount, v))
}

// PricePerMember applies equality check predicate on the "price_per_member" field. It's identical to PricePerMemberEQ.
func PricePerMember(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldPricePerMember, v))
}

// PlanNote applies equality check predicate on the "plan_note" field. It's identical to PlanNoteEQ.
func PlanNote(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldPlanNote, v))
}

// MemberCount applies equality check predicate on the "member_count" field. It's identical to MemberCountEQ.
func MemberCount(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldMemberCount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldStatus, v))
}

// OpenKey applies equality check predicate on the "open_key" field. It's identical to OpenKeyEQ.
func OpenKey(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldOpenKey, v))
}

// StatusReason applies equality check predicate on the "status_reason" field. It's identical to StatusReasonEQ.
func StatusReason(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldStatusReason, v))
}

// DeadlineAt applies equality check predicate on the "deadline_at" field. It's identical to DeadlineAtEQ.
func DeadlineAt(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldDeadlineAt, v))
}

// FormedAt applies equality check predicate on the "formed_at" field. It's identical to FormedAtEQ.
func FormedAt(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldFormedAt, v))
}

// OpenedAt applies equality check predicate on the "opened_at" field. It's identical to OpenedAtEQ.
func OpenedAt(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldOpenedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// CarpoolPlanIDEQ applies the EQ predicate on the "carpool_plan_id" field.
func CarpoolPlanIDEQ(v int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldCarpoolPlanID, v))
}

// CarpoolPlanIDNEQ applies the NEQ predicate on the "carpool_plan_id" field.
func CarpoolPlanIDNEQ(v int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldCarpoolPlanID, v))
}

// CarpoolPlanIDIn applies the In predicate on the "carpool_plan_id" field.
func CarpoolPlanIDIn(vs ...int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldCarpoolPlanID, vs...))
}

// CarpoolPlanIDNotIn applies the NotIn predicate on the "carpool_plan_id" field.
func CarpoolPlanIDNotIn(vs ...int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldCarpoolPlanID, vs...))
}

// CarpoolPlanIDGT applies the GT predicate on the "carpool_plan_id" field.
func CarpoolPlanIDGT(v int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldCarpoolPlanID, v))
}

// CarpoolPlanIDGTE applies the GTE predicate on the "carpool_plan_id" field.
func CarpoolPlanIDGTE(v int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldCarpoolPlanID, v))
}

// CarpoolPlanIDLT applies the LT predicate on the "carpool_plan_id" field.
func CarpoolPlanIDLT(v int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldCarpoolPlanID, v))
}

// CarpoolPlanIDLTE applies the LTE predicate on the "carpool_plan_id" field.
func CarpoolPlanIDLTE(v int64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldCarpoolPlanID, v))
}

// CarpoolPlanRevisionEQ applies the EQ predicate on the "carpool_plan_revision" field.
func CarpoolPlanRevisionEQ(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldCarpoolPlanRevision, v))
}

// CarpoolPlanRevisionNEQ applies the NEQ predicate on the "carpool_plan_revision" field.
func CarpoolPlanRevisionNEQ(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldCarpoolPlanRevision, v))
}

// CarpoolPlanRevisionIn applies the In predicate on the "carpool_plan_revision" field.
func CarpoolPlanRevisionIn(vs ...int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldCarpoolPlanRevision, vs...))
}

// CarpoolPlanRevisionNotIn applies the NotIn predicate on the "carpool_plan_revision" field.
func CarpoolPlanRevisionNotIn(vs ...int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldCarpoolPlanRevision, vs...))
}

// CarpoolPlanRevisionGT applies the GT predicate on the "carpool_plan_revision" field.
func CarpoolPlanRevisionGT(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldCarpoolPlanRevision, v))
}

// CarpoolPlanRevisionGTE applies the GTE predicate on the "carpool_plan_revision" field.
func CarpoolPlanRevisionGTE(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldCarpoolPlanRevision, v))
}

// CarpoolPlanRevisionLT applies the LT predicate on the "carpool_plan_revision" field.
func CarpoolPlanRevisionLT(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldCarpoolPlanRevision, v))
}

// CarpoolPlanRevisionLTE applies the LTE predicate on the "carpool_plan_revision" field.
func CarpoolPlanRevisionLTE(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldCarpoolPlanRevision, v))
}

// TargetMembersEQ applies the EQ predicate on the "target_members" field.
func TargetMembersEQ(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldTargetMembers, v))
}

// TargetMembersNEQ applies the NEQ predicate on the "target_members" field.
func TargetMembersNEQ(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldTargetMembers, v))
}

// TargetMembersIn applies the In predicate on the "target_members" field.
func TargetMembersIn(vs ...int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldTargetMembers, vs...))
}

// TargetMembersNotIn applies the NotIn predicate on the "target_members" field.
func TargetMembersNotIn(vs ...int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldTargetMembers, vs...))
}

// TargetMembersGT applies the GT predicate on the "target_members" field.
func TargetMembersGT(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldTargetMembers, v))
}

// TargetMembersGTE applies the GTE predicate on the "target_members" field.
func TargetMembersGTE(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldTargetMembers, v))
}

// TargetMembersLT applies the LT predicate on the "target_members" field.
func TargetMembersLT(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldTargetMembers, v))
}

// TargetMembersLTE applies the LTE predicate on the "target_members" field.
func TargetMembersLTE(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldTargetMembers, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldTotalAmount, v))
}

// PricePerMemberEQ applies the EQ predicate on the "price_per_member" field.
func PricePerMemberEQ(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldPricePerMember, v))
}

// PricePerMemberNEQ applies the NEQ predicate on the "price_per_member" field.
func PricePerMemberNEQ(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldPricePerMember, v))
}

// PricePerMemberIn applies the In predicate on the "price_per_member" field.
func PricePerMemberIn(vs ...float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldPricePerMember, vs...))
}

// PricePerMemberNotIn applies the NotIn predicate on the "price_per_member" field.
func PricePerMemberNotIn(vs ...float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldPricePerMember, vs...))
}

// PricePerMemberGT applies the GT predicate on the "price_per_member" field.
func PricePerMemberGT(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldPricePerMember, v))
}

// PricePerMemberGTE applies the GTE predicate on the "price_per_member" field.
func PricePerMemberGTE(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldPricePerMember, v))
}

// PricePerMemberLT applies the LT predicate on the "price_per_member" field.
func PricePerMemberLT(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldPricePerMember, v))
}

// PricePerMemberLTE applies the LTE predicate on the "price_per_member" field.
func PricePerMemberLTE(v float64) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldPricePerMember, v))
}

// PlanNoteEQ applies the EQ predicate on the "plan_note" field.
func PlanNoteEQ(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldPlanNote, v))
}

// PlanNoteNEQ applies the NEQ predicate on the "plan_note" field.
func PlanNoteNEQ(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldPlanNote, v))
}

// PlanNoteIn applies the In predicate on the "plan_note" field.
func PlanNoteIn(vs ...string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldPlanNote, vs...))
}

// PlanNoteNotIn applies the NotIn predicate on the "plan_note" field.
func PlanNoteNotIn(vs ...string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldPlanNote, vs...))
}

// PlanNoteGT applies the GT predicate on the "plan_note" field.
func PlanNoteGT(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldPlanNote, v))
}

// PlanNoteGTE applies the GTE predicate on the "plan_note" field.
func PlanNoteGTE(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldPlanNote, v))
}

// PlanNoteLT applies the LT predicate on the "plan_note" field.
func PlanNoteLT(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldPlanNote, v))
}

// PlanNoteLTE applies the LTE predicate on the "plan_note" field.
func PlanNoteLTE(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldPlanNote, v))
}

// PlanNoteContains applies the Contains predicate on the "plan_note" field.
func PlanNoteContains(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldContains(FieldPlanNote, v))
}

// PlanNoteHasPrefix applies the HasPrefix predicate on the "plan_note" field.
func PlanNoteHasPrefix(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldHasPrefix(FieldPlanNote, v))
}

// PlanNoteHasSuffix applies the HasSuffix predicate on the "plan_note" field.
func PlanNoteHasSuffix(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldHasSuffix(FieldPlanNote, v))
}

// PlanNoteEqualFold applies the EqualFold predicate on the "plan_note" field.
func PlanNoteEqualFold(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEqualFold(FieldPlanNote, v))
}

// PlanNoteContainsFold applies the ContainsFold predicate on the "plan_note" field.
func PlanNoteContainsFold(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldContainsFold(FieldPlanNote, v))
}

// MemberCountEQ applies the EQ predicate on the "member_count" field.
func MemberCountEQ(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldMemberCount, v))
}

// MemberCountNEQ applies the NEQ predicate on the "member_count" field.
func MemberCountNEQ(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldMemberCount, v))
}

// MemberCountIn applies the In predicate on the "member_count" field.
func MemberCountIn(vs ...int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldMemberCount, vs...))
}

// MemberCountNotIn applies the NotIn predicate on the "member_count" field.
func MemberCountNotIn(vs ...int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldMemberCount, vs...))
}

// MemberCountGT applies the GT predicate on the "member_count" field.
func MemberCountGT(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldMemberCount, v))
}

// MemberCountGTE applies the GTE predicate on the "member_count" field.
func MemberCountGTE(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldMemberCount, v))
}

// MemberCountLT applies the LT predicate on the "member_count" field.
func MemberCountLT(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldMemberCount, v))
}

// MemberCountLTE applies the LTE predicate on the "member_count" field.
func MemberCountLTE(v int) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldMemberCount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldContainsFold(FieldStatus, v))
}

// OpenKeyEQ applies the EQ predicate on the "open_key" field.
func OpenKeyEQ(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldOpenKey, v))
}

// OpenKeyNEQ applies the NEQ predicate on the "open_key" field.
func OpenKeyNEQ(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldOpenKey, v))
}

// OpenKeyIn applies the In predicate on the "open_key" field.
func OpenKeyIn(vs ...string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldOpenKey, vs...))
}

// OpenKeyNotIn applies the NotIn predicate on the "open_key" field.
func OpenKeyNotIn(vs ...string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldOpenKey, vs...))
}

// OpenKeyGT applies the GT predicate on the "open_key" field.
func OpenKeyGT(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldOpenKey, v))
}

// OpenKeyGTE applies the GTE predicate on the "open_key" field.
func OpenKeyGTE(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldOpenKey, v))
}

// OpenKeyLT applies the LT predicate on the "open_key" field.
func OpenKeyLT(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldOpenKey, v))
}

// OpenKeyLTE applies the LTE predicate on the "open_key" field.
func OpenKeyLTE(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldOpenKey, v))
}

// OpenKeyContains applies the Contains predicate on the "open_key" field.
func OpenKeyContains(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldContains(FieldOpenKey, v))
}

// OpenKeyHasPrefix applies the HasPrefix predicate on the "open_key" field.
func OpenKeyHasPrefix(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldHasPrefix(FieldOpenKey, v))
}

// OpenKeyHasSuffix applies the HasSuffix predicate on the "open_key" field.
func OpenKeyHasSuffix(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldHasSuffix(FieldOpenKey, v))
}

// OpenKeyIsNil applies the IsNil predicate on the "open_key" field.
func OpenKeyIsNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIsNull(FieldOpenKey))
}

// OpenKeyNotNil applies the NotNil predicate on the "open_key" field.
func OpenKeyNotNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotNull(FieldOpenKey))
}

// OpenKeyEqualFold applies the EqualFold predicate on the "open_key" field.
func OpenKeyEqualFold(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEqualFold(FieldOpenKey, v))
}

// OpenKeyContainsFold applies the ContainsFold predicate on the "open_key" field.
func OpenKeyContainsFold(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldContainsFold(FieldOpenKey, v))
}

// StatusReasonEQ applies the EQ predicate on the "status_reason" field.
func StatusReasonEQ(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldStatusReason, v))
}

// StatusReasonNEQ applies the NEQ predicate on the "status_reason" field.
func StatusReasonNEQ(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldStatusReason, v))
}

// StatusReasonIn applies the In predicate on the "status_reason" field.
func StatusReasonIn(vs ...string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldStatusReason, vs...))
}

// StatusReasonNotIn applies the NotIn predicate on the "status_reason" field.
func StatusReasonNotIn(vs ...string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldStatusReason, vs...))
}

// StatusReasonGT applies the GT predicate on the "status_reason" field.
func StatusReasonGT(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldStatusReason, v))
}

// StatusReasonGTE applies the GTE predicate on the "status_reason" field.
func StatusReasonGTE(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldStatusReason, v))
}

// StatusReasonLT applies the LT predicate on the "status_reason" field.
func StatusReasonLT(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldStatusReason, v))
}

// StatusReasonLTE applies the LTE predicate on the "status_reason" field.
func StatusReasonLTE(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldStatusReason, v))
}

// StatusReasonContains applies the Contains predicate on the "status_reason" field.
func StatusReasonContains(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldContains(FieldStatusReason, v))
}

// StatusReasonHasPrefix applies the HasPrefix predicate on the "status_reason" field.
func StatusReasonHasPrefix(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldHasPrefix(FieldStatusReason, v))
}

// StatusReasonHasSuffix applies the HasSuffix predicate on the "status_reason" field.
func StatusReasonHasSuffix(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldHasSuffix(FieldStatusReason, v))
}

// StatusReasonIsNil applies the IsNil predicate on the "status_reason" field.
func StatusReasonIsNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIsNull(FieldStatusReason))
}

// StatusReasonNotNil applies the NotNil predicate on the "status_reason" field.
func StatusReasonNotNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotNull(FieldStatusReason))
}

// StatusReasonEqualFold applies the EqualFold predicate on the "status_reason" field.
func StatusReasonEqualFold(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEqualFold(FieldStatusReason, v))
}

// StatusReasonContainsFold applies the ContainsFold predicate on the "status_reason" field.
func StatusReasonContainsFold(v string) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldContainsFold(FieldStatusReason, v))
}

// DeadlineAtEQ applies the EQ predicate on the "deadline_at" field.
func DeadlineAtEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldDeadlineAt, v))
}

// DeadlineAtNEQ applies the NEQ predicate on the "deadline_at" field.
func DeadlineAtNEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldDeadlineAt, v))
}

// DeadlineAtIn applies the In predicate on the "deadline_at" field.
func DeadlineAtIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldDeadlineAt, vs...))
}

// DeadlineAtNotIn applies the NotIn predicate on the "deadline_at" field.
func DeadlineAtNotIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldDeadlineAt, vs...))
}

// DeadlineAtGT applies the GT predicate on the "deadline_at" field.
func DeadlineAtGT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldDeadlineAt, v))
}

// DeadlineAtGTE applies the GTE predicate on the "deadline_at" field.
func DeadlineAtGTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldDeadlineAt, v))
}

// DeadlineAtLT applies the LT predicate on the "deadline_at" field.
func DeadlineAtLT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldDeadlineAt, v))
}

// DeadlineAtLTE applies the LTE predicate on the "deadline_at" field.
func DeadlineAtLTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldDeadlineAt, v))
}

// DeadlineAtIsNil applies the IsNil predicate on the "deadline_at" field.
func DeadlineAtIsNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIsNull(FieldDeadlineAt))
}

// DeadlineAtNotNil applies the NotNil predicate on the "deadline_at" field.
func DeadlineAtNotNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotNull(FieldDeadlineAt))
}

// FormedAtEQ applies the EQ predicate on the "formed_at" field.
func FormedAtEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldFormedAt, v))
}

// FormedAtNEQ applies the NEQ predicate on the "formed_at" field.
func FormedAtNEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldFormedAt, v))
}

// FormedAtIn applies the In predicate on the "formed_at" field.
func FormedAtIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldFormedAt, vs...))
}

// FormedAtNotIn applies the NotIn predicate on the "formed_at" field.
func FormedAtNotIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldFormedAt, vs...))
}

// FormedAtGT applies the GT predicate on the "formed_at" field.
func FormedAtGT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldFormedAt, v))
}

// FormedAtGTE applies the GTE predicate on the "formed_at" field.
func FormedAtGTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldFormedAt, v))
}

// FormedAtLT applies the LT predicate on the "formed_at" field.
func FormedAtLT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldFormedAt, v))
}

// FormedAtLTE applies the LTE predicate on the "formed_at" field.
func FormedAtLTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldFormedAt, v))
}

// FormedAtIsNil applies the IsNil predicate on the "formed_at" field.
func FormedAtIsNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIsNull(FieldFormedAt))
}

// FormedAtNotNil applies the NotNil predicate on the "formed_at" field.
func FormedAtNotNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotNull(FieldFormedAt))
}

// OpenedAtEQ applies the EQ predicate on the "opened_at" field.
func OpenedAtEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldOpenedAt, v))
}

// OpenedAtNEQ applies the NEQ predicate on the "opened_at" field.
func OpenedAtNEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldOpenedAt, v))
}

// OpenedAtIn applies the In predicate on the "opened_at" field.
func OpenedAtIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldOpenedAt, vs...))
}

// OpenedAtNotIn applies the NotIn predicate on the "opened_at" field.
func OpenedAtNotIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldOpenedAt, vs...))
}

// OpenedAtGT applies the GT predicate on the "opened_at" field.
func OpenedAtGT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldOpenedAt, v))
}

// OpenedAtGTE applies the GTE predicate on the "opened_at" field.
func OpenedAtGTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldOpenedAt, v))
}

// OpenedAtLT applies the LT predicate on the "opened_at" field.
func OpenedAtLT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldOpenedAt, v))
}

// OpenedAtLTE applies the LTE predicate on the "opened_at" field.
func OpenedAtLTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldOpenedAt, v))
}

// OpenedAtIsNil applies the IsNil predicate on the "opened_at" field.
func OpenedAtIsNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIsNull(FieldOpenedAt))
}

// OpenedAtNotNil applies the NotNil predicate on the "opened_at" field.
func OpenedAtNotNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotNull(FieldOpenedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotNull(FieldExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOrders applies the HasEdge predicate on the "orders" edge.
func HasOrders() predicate.CarpoolGroup {
	return predicate.CarpoolGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrdersWith applies the HasEdge predicate on the "orders" edge with a given conditions (other predicates).
func HasOrdersWith(preds ...predicate.PaymentOrder) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(func(s *sql.Selector) {
		step := newOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CarpoolGroup) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CarpoolGroup) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CarpoolGroup) predicate.CarpoolGroup {
	return predicate.CarpoolGroup(sql.NotPredicates(p))
}
